export const BAPTISMAL_VOWS = {
  en: [
    'I believe in God the Father, in His Son Jesus Christ, and in the Holy Spirit.',
    'I accept the death of Jesus Christ on Calvary as the atoning sacrifice for my sins.',
    'I accept Jesus Christ as my personal Savior and Lord.',
    'I accept by faith the righteousness of Christ, recognizing Him as my Intercessor in the heavenly sanctuary.',
    'I believe that the Bible is God’s inspired Word, the only rule of faith and practice. I covenant to spend time in prayer and Bible study.',
    'I accept the Ten Commandments as a transcript of the character of God and a revelation of His will. It is my purpose by the power of the indwelling Christ to keep this law, including the fourth commandment, which requires the observance of the seventh day of the week as the Sabbath of the Lord and as the memorial of Creation.',
    'I look forward to the soon coming of Jesus and the blessed hope.',
    'I accept the biblical teaching of spiritual gifts and believe that the gift of prophecy is one of the identifying marks of the remnant church.',
    'I believe in church organization. It is my purpose to support the church by my tithes and offerings and by my personal effort and influence.',
    'I believe that my body is the temple of the Holy Spirit; I will honor God by caring for it, abstaining from use of alcohol, tobacco, and unclean foods.',
    'I know and understand the fundamental Bible principles as taught by the Seventh-day Adventist Church. I purpose, by the grace of God, to fulfill His will by ordering my life in harmony with these principles.',
    'I accept the New Testament teaching of baptism by immersion.',
    'I accept that the Seventh-day Adventist Church is the remnant church of Bible prophecy.',
  ],
  zh: [
    '我相信獨一的上帝，祂是聖父、聖子、聖靈三位同時永在上帝的結合。',
    '我接受耶穌基督在髑髏地的死，乃是為我贖罪而作的犧牲。',
    '我接受耶穌基督為我個人的救主，相信上帝在基督裡，已經赦免我的罪過。',
    '我願意接受基督而因信稱義，承認祂是我天上聖所的中保。',
    '我相信聖經乃是上帝所默示的聖言，乃是基督徒信仰與行為的唯一準則。',
    '我接受十條誡命為上帝聖德的副本，也是祂旨意的啟示。',
    '我盼望主耶穌快來，作為我的洪福之望。',
    '我接受聖經中有關屬靈恩賜的教訓，並且相信這種預言的恩賜。',
    '我相信教會的組織。我願意立志以十分之一和其他捐獻支持教會。',
    '我相信我的身體乃是聖靈的殿。我願意留心愛護身體，不用任何有害之物。',
    '我明白基督復臨安息日會所教導的聖經基本原則。',
    '我接受新約聖經所教導的全身入水的浸禮。',
    '我相信基督復臨安息日會乃是聖經所啟示的餘民教會。',
  ],
  'zh-cn': [
    '我相信独一的上帝，祂是圣父、圣子、圣灵三位同时永在上帝的结合。',
    '我接受耶稣基督在髑髅地的死，乃是为我赎罪而作的牺牲。',
    '我接受耶稣基督为我个人的救主，相信上帝在基督里，已经赦免我的罪过。',
    '我愿意接受基督而因信称义，承认祂是我天上圣所的中保。',
    '我相信圣经乃是上帝所默示的圣言，乃是基督徒信仰与行为的唯一准则。',
    '我接受十条诫命为上帝圣德的副本，也是祂旨意的启示。',
    '我盼望主耶稣快来，作为我的洪福之望。',
    '我接受圣经中有关属灵恩赐的教训，并且相信这种预言的恩赐。',
    '我相信教会的组织。我愿意立志以十分之一和其他捐献支持教会。',
    '我相信我的身体乃是圣灵的殿。我愿意留心爱护身体，不用任何有害之物。',
    '我明白基督复临安息日会所教导的圣经基本原则。',
    '我接受新约圣经所教导的全身入水的浸礼。',
    '我相信基督复临安息日会乃是圣经所启示的余民教会。',
  ],
  es: [
    'Creo en un solo Dios: Padre, Hijo y Espíritu Santo.',
    'Acepto la muerte de Jesucristo en el Calvario como el sacrificio expiatorio por mis pecados.',
    'Acepto a Jesucristo como mi Salvador y Señor personal.',
    'Acepto por la fe la justicia de Cristo, reconociéndolo como mi Intercesor en el santuario celestial.',
    'Creo que la Biblia es la Palabra inspirada de Dios, la única regla de fe y práctica.',
    'Acepto los Diez Mandamientos como una transcripción del carácter de Dios y una revelación de su voluntad.',
    'Espero con anhelo la pronta venida de Jesús y la esperanza bienaventurada.',
    'Acepto la enseñanza bíblica de los dones espirituales y creo que el don de profecía es una de las marcas identificativas de la iglesia remanente.',
    'Creo en la organización de la iglesia y me propongo apoyarla con mis diezmos y ofrendas.',
    'Creo que mi cuerpo es el templo del Espíritu Santo; lo cuidaré evitando cosas perjudiciales.',
    'Conozco y entiendo los principios bíblicos fundamentales enseñados por la Iglesia Adventista del Séptimo Día.',
    'Acepto la enseñanza del Nuevo Testamento del bautismo por inmersión.',
    'Acepto que la Iglesia Adventista del Séptimo Día es la iglesia remanente de la profecía bíblica.',
  ],
};

export const TEN_COMMANDMENTS = {
  en: [
    'You shall have no other gods before Me.',
    'You shall not make for yourself an idol.',
    'You shall not misuse the name of the LORD your God.',
    'Remember the Sabbath day by keeping it holy.',
    'Honor your father and your mother.',
    'You shall not murder.',
    'You shall not commit adultery.',
    'You shall not steal.',
    'You shall not give false testimony against your neighbor.',
    'You shall not covet.',
  ],
  zh: [
    '除了我以外，你不可有別的神。',
    '不可為自己雕刻偶像。',
    '不可妄稱耶和華你上帝的名。',
    '當記念安息日，守為聖日。',
    '當孝敬父母。',
    '不可殺人。',
    '不可姦淫。',
    '不可偷盜。',
    '不可作假見證陷害人。',
    '不可貪戀人的房屋與妻子。',
  ],
  'zh-cn': [
    '除了我以外，你不可有别的神。',
    '不可为自己雕刻偶像。',
    '不可妄称耶和华你上帝的名。',
    '当纪念安息日，守为圣日。',
    '当孝敬父母。',
    '不可杀人。',
    '不可奸淫。',
    '不可偷盗。',
    '不可作假见证陷害人。',
    '不可贪恋人的房屋与妻子。',
  ],
  es: [
    'No tendrás dioses ajenos delante de mí.',
    'No te harás imagen, ni ninguna semejanza.',
    'No tomarás el nombre de Jehová tu Dios en vano.',
    'Acuérdate del día de reposo para santificarlo.',
    'Honra a tu padre y a tu madre.',
    'No matarás.',
    'No cometerás adulterio.',
    'No hurtarás.',
    'No hablarás contra tu prójimo falso testimonio.',
    'No codiciarás.',
  ],
};

export const DIETARY_PRINCIPLES = {
  en: {
    land: 'Land animals must have divided hooves and chew the cud.',
    water: 'Water creatures must have fins and scales.',
    birds: 'Birds of prey and scavengers are avoided.',
    lifestyle:
      'We avoid alcohol, tobacco, and harmful drugs to honor God with our bodies.',
  },
  zh: {
    land: '陸地上的動物：需具有分蹄和倒嚼（反芻）兩個特徵。',
    water: '水中的生物：需具有有鱗和有翅（魚鰭）兩個特徵。',
    birds: '雀鳥：不吃食腐肉的鳥類。',
    lifestyle: '煙、酒、毒品對身體極度有害，身為上帝的殿，我們不可以使用。',
  },
  'zh-cn': {
    land: '陆地上的动物：需具有分蹄和倒嚼（反刍）两个特征。',
    water: '水中的生物：需具有有鳞和有翅（鱼鳍）两个特征。',
    birds: '雀鸟：不吃食腐肉的鸟类。',
    lifestyle: '烟、酒、毒品对身体极度有害，身为上帝的殿，我们不可以使用。',
  },
  es: {
    land: 'Los animales terrestres deben tener pezuña hendida y rumiar.',
    water: 'Las criaturas acuáticas deben tener aletas y escamas.',
    birds: 'Se evitan las aves de rapiña y carroñeras.',
    lifestyle:
      'Evitamos el alcohol, el tabaco y las drogas dañinas para honrar a Dios con nuestro cuerpo.',
  },
};

export const FOUR_PILLARS = {
  en: [
    { title: 'Truth', desc: 'Study the Bible to understand our fundamental beliefs.' },
    { title: 'Fellowship', desc: 'Participate in Sabbath worship and community groups.' },
    { title: 'Sacraments', desc: 'Baptism, Foot Washing, and the Lord’s Supper.' },
    { title: 'Prayer', desc: 'Daily communication with God through reading and prayer.' },
  ],
  zh: [
    { title: '真理', desc: '研讀聖經以了解我們的基本信仰。' },
    { title: '團契', desc: '親自參加教會的安息日崇拜與小組聚會。' },
    { title: '聖禮', desc: '洗禮、洗腳禮與聖餐禮。' },
    { title: '祈禱', desc: '每天與上帝交通，建立屬靈生活。' },
  ],
  'zh-cn': [
    { title: '真理', desc: '研读圣经以了解我们的基本信仰。' },
    { title: '团契', desc: '亲自参加教会的安息日崇拜与小组聚会。' },
    { title: '圣礼', desc: '洗礼、洗脚礼与圣餐礼。' },
    { title: '祈祷', desc: '每天与上帝交通，建立属灵生活。' },
  ],
  es: [
    {
      title: 'Verdad',
      desc: 'Estudiar la Biblia para entender nuestras creencias fundamentales.',
    },
    {
      title: 'Compañerismo',
      desc: 'Participar en la adoración sabática y grupos comunitarios.',
    },
    { title: 'Sacramentos', desc: 'Bautismo, Lavamiento de pies y la Cena del Señor.' },
    {
      title: 'Oración',
      desc: 'Comunicación diaria con Dios a través de la lectura y oración.',
    },
  ],
};
