/**
 * SDA Hymnal 1985 Edition - English Hymn Metadata
 *
 * This file contains a structured dataset of metadata for the Seventh-day Adventist
 * Hymnal (1985 edition), mapping sequential indices to titles and factual reference
 * points for application routing and lookup features.
 *
 * LEGAL COMPLIANCE & REPOSITORY HOSTING NOTE:
 * This dataset consists strictly of non-copyrightable metadata and factual listings
 * (sequential numbers, brief titles, and historical scripture mappings). Under U.S.
 * Copyright Law (U.S. Copyright Office Circular 34), short phrases, titles, and mechanical
 * numbering systems lack the creative authorship required for copyright protection.
 * Furthermore, per Feist Publications, Inc. v. Rural Telephone Service Co., 499 U.S. 340 (1991),
 * purely factual compilations and cross-references are not eligible for copyright. Because
 * this file omits protected creative works (such as musical notation or proprietary lyric
 * texts), it is public factual data eligible for open distribution and public hosting.
 *
 * EXTERNAL HYPERLINK ROUTING POLICY:
 * To provide the congregation with access to sheet music without hosting copyrighted
 * files, this application utilizes a standard redirect architecture to external, public
 * web pages on HymnsForWorship.org (an educational resource curated by a credentialed
 * SDA music educator). In accordance with established legal precedent (Perfect 10, Inc. v. Amazon.com, Inc.),
 * standard hyperlinking to a publicly accessible webpage does not constitute copyright infringement.
 *
 * IMPLEMENTATION CONSTRAINTS (DEVELOPER DISCLOSURE):
 * - All external links MUST open in the device's native web browser (Safari/Chrome).
 *   Do NOT embed sheets via internal webviews, frames, or inline scrapers.
 * - Do NOT hotlink directly to raw asset files (e.g., paths ending in .png, .jpg, or .pdf).
 *   You may only link to the official user-facing HTML landing pages. This respects the
 *   hosting platform's terms of use and preserves necessary copyright attribution context.
 */

import { openURL } from './ExternalLinks';

export const openHymnal = (hymnNumber?: string | number) => {
  const hId =
    typeof hymnNumber === 'string' || typeof hymnNumber === 'number' ? hymnNumber : '';

  if (hId === '') {
    return openURL(
      'https://hymnsforworship.org/sda-hymnal/the-seventh-day-adventist-hymnal-1985-edition/',
    );
  }

  return openURL(`https://hymnsforworship.org/sdah-${hId.toString().padStart(3, '0')}`);
};

export interface HymnEntry {
  title: string;
  scriptureReference?: string;
}

/**
 * Represents a hymn entry with its number included,
 * used primarily for UI components and lists.
 */
export interface HydratedHymn extends HymnEntry {
  number: number;
}

export interface SDAHymnalData {
  // We use a Record where the key is the hymn number for O(1) lookups
  en: Record<number, HymnEntry>;
  // Add other languages here if supported in the future
}

/**
 * Converts the Record-based hymnal data into a sorted array.
 * This is the preferred way to "fetch" data for FlatLists or search screens.
 */
export const getSortedHymns = (lang: keyof SDAHymnalData = 'en'): HydratedHymn[] => {
  return Object.entries(SDA_HYMNAL_1985[lang])
    .map(([num, data]) => ({
      number: parseInt(num, 10),
      ...data,
    }))
    .sort((a, b) => a.number - b.number);
};

export const SDA_HYMNAL_1985: SDAHymnalData = {
  en: {
    1: { title: 'Praise to the Lord', scriptureReference: 'Psalm 103:2-5' },
    2: { title: 'All Creatures of Our God and King' },
    3: { title: 'God Himself Is With Us' },
    4: { title: 'Immortal, Invisible, God Only Wise', scriptureReference: 'Psalm 103' },
    5: { title: 'All My Hope on God Is Founded' },
    6: { title: 'O Worship the Lord' },
    7: { title: 'The Lord in Zion Reigneth' },
    8: { title: 'We Gather Together' },
    9: { title: 'Let All the World in Every Corner Sing' },
    10: { title: 'Come, Christians, Join to Sing' },
    11: { title: 'The God of Abraham Praise', scriptureReference: 'Exodus 3:14-15' },
    12: { title: 'Joyful, Joyful, We Adore Thee' },
    13: { title: 'New Songs of Celebration Render', scriptureReference: 'Psalm 98' },
    14: { title: 'Let Us Praise the Name of the Lord' },
    15: { title: 'My Maker and My King' },
    16: { title: 'All People That on Earth Do Dwell', scriptureReference: 'Psalm 100' },
    17: { title: 'Lord of All Being, Throned Afar' },
    18: { title: 'O Morning Star, How Fair and Bright' },
    19: { title: 'O Sing a New Song to the Lord', scriptureReference: 'Psalm 98' },
    20: { title: 'O Praise Ye the Lord', scriptureReference: 'Psalm 150' },
    21: {
      title: 'Immortal, Invisible, God Only Wise',
      scriptureReference: '1 Timothy 1:17',
    },
    22: { title: 'God Is Our Song', scriptureReference: 'Psalm 118:14' },
    23: { title: 'Now the Joyful Bells A-Ringing', scriptureReference: 'Psalm 148:9' },
    24: { title: 'Every Star Shall Sing a Carol' },
    25: { title: 'Praise the Lord, His Glories Show', scriptureReference: 'Psalm 150' },
    26: {
      title: 'Praise the Lord! You Heavens Adore Him',
      scriptureReference: 'Psalm 148',
    },
    27: { title: 'Rejoice, Ye Pure in Heart!', scriptureReference: 'Psalm 20:5' },
    28: { title: 'Praise We the Lord' },
    29: { title: 'Sing Praise to God' },
    30: { title: 'Holy God, We Praise Your Name' },
    31: { title: 'Tell Out, My Soul' },
    32: { title: 'When in Our Music God Is Glorified' },
    33: { title: 'Sing a New Song to the Lord', scriptureReference: 'Psalm 98' },
    34: { title: 'Wake the Song' },
    35: { title: 'With Songs and Honors', scriptureReference: 'Psalm 147' },
    36: { title: 'O Thou in Whose Presence' },
    37: { title: 'O Sing, My Soul, Your Maker’s Praise', scriptureReference: 'Psalm 34' },
    38: { title: 'Arise, My Soul, Arise!' },
    39: { title: 'Lord, in the Morning', scriptureReference: 'Psalm 5' },
    40: { title: 'The Dawn of God’s Dear Sabbath' },
    41: { title: 'O Splendor of God’s Glory Bright', scriptureReference: 'Hebrews 1:3' },
    42: { title: 'Now That Daylight Fills the Sky' },
    43: { title: 'When Morning Gilds the Skies', scriptureReference: 'Psalm 150:6' },
    44: { title: 'Morning Has Broken' },
    45: { title: 'Open Now Thy Gates of Beauty' },
    46: { title: 'Abide With Me, ‘Tis Eventide' },
    47: { title: 'God, Who Made the Earth and Heaven' },
    48: { title: 'Softly Now the Light of Day' },
    49: { title: 'Savior, Breathe an Evening Blessing' },
    50: { title: 'Abide With Me', scriptureReference: 'Luke 24:29' },
    51: { title: 'Day Is Dying in the West' },
    52: { title: 'Now the Day Is Over' },
    53: { title: 'All Praise to Thee', scriptureReference: 'Mark 10:14' },
    54: { title: 'O Gladsome Light' },
    55: { title: 'Jesus, Tender Shepherd, Hear Me' },
    56: { title: 'The Day Thou Gavest' },
    57: { title: 'Now All the Woods Are Sleeping', scriptureReference: 'Psalm 3:5' },
    58: { title: 'Hark, the Vesper Hymn Is Stealing' },
    59: { title: 'Great Our Joy as Now We Gather' },
    60: { title: 'Blessed Jesus, at Thy Word' },
    61: { title: 'God Is Here!' },
    62: { title: 'How Lovely Is Thy Dwelling Place', scriptureReference: 'Psalm 84' },
    63: { title: 'O Come, Let Us Sing to the Lord', scriptureReference: 'Psalm 95:1-6' },
    64: { title: 'Lord, Dismiss Us With Thy Blessing' },
    65: { title: 'God Be With You', scriptureReference: '2 Corinthians 13:11' },
    66: { title: 'God Be With You' },
    67: { title: 'O Lord, Now Let Your Servant', scriptureReference: 'Luke 2:29-32' },
    68: { title: 'On Our Way Rejoicing', scriptureReference: 'Revelation 1:7' },
    69: { title: 'Lord, Make Us More Holy' },
    70: { title: 'Praise Ye the Father', scriptureReference: '2 Corinthians 13:14' },
    71: { title: 'Come, Thou Almighty King' },
    72: { title: 'Creator of the Stars of Night' },
    73: { title: 'Holy, Holy, Holy', scriptureReference: 'Revelation 4:8-11' },
    74: { title: 'Like a River Glorious', scriptureReference: 'Isaiah 48:11' },
    75: { title: 'The Wonder of It All' },
    76: { title: 'O Love That Wilt Not Let Me Go' },
    77: { title: 'O Love of God Most Full' },
    78: { title: 'For God So Loved Us' },
    79: { title: 'O Love of God, How Strong and True!' },
    80: { title: 'O World of God' },
    81: { title: 'Though I Speak With Tongues' },
    82: { title: 'Before Jehovah’s Awful Throne', scriptureReference: 'Psalm 100' },
    83: { title: 'O Worship the King', scriptureReference: 'Psalm 104' },
    84: { title: 'God the Omnipotent' },
    85: { title: 'Eternal Father, Strong to Save' },
    86: { title: 'How Great Thou Art' },
    87: { title: 'God Who Spoke in the Beginning' },
    88: { title: 'I Sing the Mighty Power of God', scriptureReference: 'Genesis 1' },
    89: { title: 'Let All on Earth Their Voices Raise', scriptureReference: 'Psalm 96' },
    90: { title: 'Eternal God, Whose Power Upholds' },
    91: { title: 'Ye Watchers and Ye Holy Ones' },
    92: { title: 'This Is My Father’s World' },
    93: { title: 'All Things Bright and Beautiful' },
    94: { title: 'Nature With Open Volume Stands' },
    95: { title: 'Spring Has Now Unwrapped the Flowers' },
    96: { title: 'The Spacious Firmament', scriptureReference: 'Psalm 19' },
    97: { title: 'Lord of the Boundless Curves of Space' },
    98: { title: 'Can You Count the Stars?' },
    99: { title: 'God Will Take Care of You', scriptureReference: '1 Peter 5:7' },
    100: {
      title: 'Great Is Thy Faithfulness',
      scriptureReference: 'Lamentations 3:22-23',
    },
    101: { title: 'Children of the Heavenly Father' },
    102: { title: 'Unto the Hills', scriptureReference: 'Psalm 121' },
    103: { title: 'O God, Our Help', scriptureReference: 'Psalm 90' },
    104: { title: 'My Shepherd Will Supply My Need', scriptureReference: 'Psalm 23' },
    105: { title: 'Sing to the Great Jehovah’s Praise' },
    106: { title: 'Give to Our God Immortal Praise' },
    107: { title: 'God Moves in a Mysterious Way', scriptureReference: 'John 13:7' },
    108: { title: 'Amazing Grace', scriptureReference: '1 Chronicles 17:16-17' },
    109: { title: 'Marvelous Grace' },
    110: { title: 'God’s Free Mercy Streameth', scriptureReference: 'Ecclesiastes 11:7' },
    111: { title: 'It Took a Miracle' },
    112: { title: 'Let Us With a Gladsome Mind' },
    113: { title: 'As Pants the Hart', scriptureReference: 'Psalm 42:1-5' },
    114: { title: 'There’s a Wideness' },
    115: { title: 'O Come, O Come, Immanuel' },
    116: { title: 'Of the Father’s Love Begotten' },
    117: { title: 'The Advent of Our God' },
    118: { title: 'The First Noel' },
    119: { title: 'Angels From the Realms of Glory' },
    120: { title: 'There’s a Song in the Air' },
    121: { title: 'Go, Tell It on the Mountain' },
    122: { title: 'Hark! the Herald Angels Sing', scriptureReference: 'Luke 2:14' },
    123: { title: 'As With Gladness Men of Old', scriptureReference: 'Matthew 2:1-11' },
    124: { title: 'Away in a Manger' },
    125: { title: 'Joy to the World', scriptureReference: 'Psalm 98:4-9' },
    126: { title: 'In the Bleak Midwinter' },
    127: { title: 'Infant Holy, Infant Lowly', scriptureReference: 'Luke 2:7-11' },
    128: { title: 'Break Forth, O Beauteous Heavenly Light' },
    129: { title: 'As It Fell Upon a Night' },
    130: { title: 'It Came Upon the Midnight Clear', scriptureReference: 'Luke 2:13-14' },
    131: { title: 'Lo, How a Rose E’er Blooming' },
    132: { title: 'O Come, All Ye Faithful' },
    133: { title: 'Now Is Born the Divine Christ Child' },
    134: { title: 'O Jesus Sweet' },
    135: { title: 'O Little Town of Bethlehem', scriptureReference: 'Luke 2:13-14' },
    136: { title: 'Good Christians, Now Rejoice' },
    137: { title: 'We Three Kings' },
    138: { title: 'Rise Up, Shepherd, and Follow' },
    139: {
      title: 'While Shepherds Watched Their Flocks',
      scriptureReference: 'Luke 2:8-14',
    },
    140: { title: 'Thou Didst Leave Thy Throne' },
    141: { title: 'What Child Is This?' },
    142: { title: 'Angels We Have Heard on High', scriptureReference: 'Luke 2:13-17' },
    143: { title: 'Silent Night, Holy Night' },
    144: { title: 'O Sing a Song of Bethlehem' },
    145: { title: 'Songs of Thankfulness and Praise' },
    146: {
      title: 'I Think When I Read That Sweet Story',
      scriptureReference: 'Matthew 19:14-15',
    },
    147: { title: 'Christ Upon the Mountain Peak', scriptureReference: 'Mark 9:2-7' },
    148: { title: 'O Love, How Deep, How Broad' },
    149: { title: 'Once in Royal David’s City' },
    150: { title: 'Who Is He in Yonder Stall?' },
    151: { title: 'Jesus Walked This Lonesome Valley' },
    152: { title: 'Tell Me the Story of Jesus' },
    153: { title: 'Prince of Peace, Control My Will' },
    154: {
      title: 'When I Survey the Wondrous Cross (Hamburg)',
      scriptureReference: 'Galatians 6:14',
    },
    155: {
      title: 'When I Survey the Wondrous Cross (Rockingham Old)',
      scriptureReference: 'Galatians 6:14',
    },
    156: { title: 'O Sacred Head Now Wounded' },
    157: { title: 'Go to Dark Gethsemane' },
    158: { title: 'Were You There?' },
    159: { title: 'The Old Rugged Cross' },
    160: { title: 'Ride On in Majesty' },
    161: { title: 'Throned Upon the Awful Tree', scriptureReference: 'Matthew 27:45-46' },
    162: { title: 'Wondrous Love' },
    163: { title: 'At the Cross' },
    164: { title: 'There Is a Green Hill Far Away' },
    165: {
      title: 'Look, You Saints! the Sight Is Glorious',
      scriptureReference: 'Revelation 11:15',
    },
    166: { title: 'Christ the Lord Is Risen Today' },
    167: { title: 'Alleluia! Sing to Jesus' },
    168: { title: 'And Have the Bright Immensities' },
    169: { title: 'Come, You Faithful' },
    170: { title: 'Come, You Faithful' },
    171: { title: 'Thine Is the Glory' },
    172: { title: 'The Strife Is O’er' },
    173: { title: 'Good Christian Friends, Rejoice!' },
    174: { title: 'Star of Our Hope', scriptureReference: '1 Thessalonians 4:16-17' },
    175: { title: 'Now the Green Blade Rises' },
    176: { title: 'Hail the Day That Sees Him Rise' },
    177: { title: 'Jesus, Your Blood and Righteousness' },
    178: { title: 'The Unveiled Christ', scriptureReference: 'Mark 15:37-38' },
    179: {
      title: 'The Wonders of Redeeming Love',
      scriptureReference: 'Hebrews 4:14-16',
    },
    180: { title: 'O Listen to Our Wondrous Story' },
    181: { title: 'Does Jesus Care?', scriptureReference: '1 Peter 5:7' },
    182: { title: 'Christ Is Alive' },
    183: { title: 'I Will Sing of Jesus’ Love' },
    184: { title: 'Jesus Paid It All' },
    185: { title: 'Jesus Is All the World to Me' },
    186: { title: 'I’ve Found a Friend' },
    187: { title: 'Jesus, What a Friend for Sinners' },
    188: { title: 'My Song Is Love Unknown' },
    189: { title: 'All That Thrills My Soul' },
    190: { title: 'Jesus Loves Me', scriptureReference: 'Proverbs 8:17' },
    191: { title: 'Love Divine' },
    192: { title: 'O Shepherd Divine' },
    193: { title: 'Savior, Teach Me' },
    194: { title: 'Sing We of the Modern City' },
    195: { title: 'Showers of Blessing', scriptureReference: 'Ezekiel 34:26' },
    196: { title: 'Tell Me the Old, Old Story' },
    197: { title: 'The King of Love My Shepherd Is', scriptureReference: 'Psalm 23' },
    198: { title: 'And Can It Be?' },
    199: { title: 'The Head That Once Was Crowned' },
    200: { title: 'The Lord Is Coming', scriptureReference: '1 Corinthians 16:22' },
    201: { title: 'Christ Is Coming' },
    202: { title: 'Hail Him the King of Glory' },
    203: { title: 'This Is the Threefold Truth' },
    204: { title: 'Come, Thou Long-Expected Jesus' },
    205: { title: 'Gleams of the Golden Morning' },
    206: { title: 'Face to Face' },
    207: { title: 'It May Be at Morn', scriptureReference: 'Mark 13:35' },
    208: { title: 'There’ll Be No Dark Valley' },
    209: { title: 'That Glorious Day Is Coming' },
    210: {
      title: 'Wake, Awake, for Night Is Flying',
      scriptureReference: 'Matthew 25:6-7',
    },
    211: { title: 'Lo! He Comes', scriptureReference: 'Revelation 1:7' },
    212: { title: '‘Tis Almost Time for the Lord to Come' },
    213: { title: 'Jesus Is Coming Again' },
    214: { title: 'We Have This Hope' },
    215: { title: 'The King Shall Come' },
    216: { title: 'When the Roll Is Called Up Yonder' },
    217: { title: 'The Church Has Waited Long' },
    218: { title: 'When He Cometh', scriptureReference: 'Malachi 3:17' },
    219: { title: 'When Jesus Comes in Glory' },
    220: { title: 'When He Comes', scriptureReference: '1 Thessalonians 4:14-17' },
    221: { title: 'Rejoice, the Lord Is King', scriptureReference: 'Philippians 4:4' },
    222: { title: 'Hark! Ten Thousand Harps and Voices' },
    223: { title: 'Crown Him With Many Crowns', scriptureReference: 'Revelation 19:12' },
    224: { title: 'Seek Ye First' },
    225: { title: 'God Is Working His Purpose Out', scriptureReference: 'Habakkuk 2:14' },
    226: { title: 'Lift Up Your Heads' },
    227: { title: 'Jesus Shall Reign', scriptureReference: 'Psalm 72:8-19' },
    228: { title: 'A Hymn of Glory Let Us Sing' },
    229: { title: 'All Hail the Power of Jesus’ Name' },
    230: { title: 'All Glory, Laud, and Honor', scriptureReference: 'Matthew 21:8-9' },
    231: { title: 'Blest Be the King', scriptureReference: 'Mark 11:9-10' },
    232: { title: 'At the Name of Jesus', scriptureReference: 'Philippians 2:8-11' },
    233: { title: 'Christ, Whose Glory Fills the Skies' },
    234: { title: 'Christ Is the World’s Light' },
    235: {
      title: 'Christ Is Made the Sure Foundation',
      scriptureReference: 'Ephesians 2:20',
    },
    236: { title: 'I Love Thee' },
    237: { title: 'In the Cross of Christ I Glory' },
    238: { title: 'How Sweet the Name!', scriptureReference: 'Song of Solomon 1:3' },
    239: { title: 'Jesus, Priceless Treasure' },
    240: { title: 'Fairest Lord Jesus' },
    241: { title: 'Jesus, the Very Thought of Thee' },
    242: { title: 'Jesus, Thou Joy of Loving Hearts' },
    243: { title: 'King of Glory, King of Peace' },
    244: { title: 'My Song Shall Be of Jesus' },
    245: { title: 'More About Jesus' },
    246: { title: 'Worthy, Worthy Is the Lamb', scriptureReference: 'Revelation 5:12' },
    247: { title: 'Come, My Way' },
    248: { title: 'O How I Love Jesus' },
    249: { title: 'Praise Him! Praise Him!' },
    250: { title: 'O for a Thousand Tongues to Sing' },
    251: { title: 'He Lives' },
    252: { title: 'Come, Let Us Sing', scriptureReference: 'Revelation 5:9-13' },
    253: { title: 'There’s No Other Name Like Jesus', scriptureReference: 'Acts 4:12' },
    254: { title: 'The Great Physician Now Is Near' },
    255: { title: 'I Cannot Tell Why' },
    256: { title: 'Ye Servants of God' },
    257: { title: 'Come Down, O Love Divine' },
    258: { title: 'Baptize Us Anew' },
    259: { title: 'Draw Us in the Spirit’s Tether' },
    260: { title: 'Hover O’er Me, Holy Spirit' },
    261: { title: 'The Spirit of the Lord Revealed' },
    262: { title: 'Sweet, Sweet Spirit' },
    263: { title: 'Fire of God, Thou Sacred Flame' },
    264: { title: 'O for That Flame of Living Fire' },
    265: { title: 'Breathe on Me, Breath of God' },
    266: { title: 'Spirit of God' },
    267: { title: 'Spirit Divine' },
    268: { title: 'Holy Spirit, Light Divine' },
    269: { title: 'Come, Holy Spirit' },
    270: { title: 'O Holy Dove of God Descending' },
    271: { title: 'Break Thou the Bread of Life', scriptureReference: 'Matthew 14:19' },
    272: { title: 'Give Me the Bible' },
    273: {
      title: 'Lord, I Have Made Thy Word My Choice',
      scriptureReference: 'Psalm 119:111',
    },
    274: { title: 'O Word of God Incarnate' },
    275: { title: 'O God of Light' },
    276: { title: 'Thanks to God' },
    277: { title: 'For Your Holy Book We Thank You' },
    278: { title: 'Lord Jesus, Once You Spoke to Men' },
    279: { title: 'Only Trust Him' },
    280: { title: 'Come, Ye Sinners' },
    281: { title: 'I Gave My Life for Thee' },
    282: { title: 'I Hear Thy Welcome Voice' },
    283: { title: 'O Jesus, Thou Art Standing' },
    284: { title: 'For You I Am Praying' },
    285: { title: 'Jesus Calls Us' },
    286: { title: 'Wonderful Words of Life' },
    287: { title: 'Softly and Tenderly' },
    288: { title: 'I Am Going to Calvary' },
    289: { title: 'The Savior Is Waiting' },
    290: { title: 'Turn Your Eyes Upon Jesus' },
    291: { title: 'We Have Not Known Thee' },
    292: { title: 'Jesus, I Come' },
    293: { title: 'Heavenly Father, Bless Us Now' },
    294: { title: 'Power in the Blood' },
    295: { title: 'Chief of Sinners' },
    296: { title: 'Lord, I’m Coming Home' },
    297: { title: 'God Be Merciful to Me', scriptureReference: 'Psalm 51' },
    298: { title: 'I Lay My Sins on Jesus' },
    299: { title: 'Forgive Our Sins as We Forgive', scriptureReference: 'Matthew 6:12' },
    300: { title: 'Rock of Ages' },
    301: { title: 'Nearer, Still Nearer' },
    302: { title: 'Deeper Yet' },
    303: { title: 'Beneath the Cross of Jesus', scriptureReference: 'Proverbs 14:26' },
    304: { title: 'Faith of Our Fathers' },
    305: { title: 'Give Me Jesus' },
    306: { title: 'Draw Me Nearer' },
    307: { title: 'I Am Coming to the Cross' },
    308: { title: 'Wholly Thine' },
    309: { title: 'I Surrender All' },
    310: { title: 'I Would Draw Nearer to Jesus' },
    311: { title: 'I Would Be Like Jesus' },
    312: { title: 'Near the Cross' },
    313: { title: 'Just as I Am' },
    314: { title: 'Just as I Am' },
    315: { title: 'O for a Closer Walk!' },
    316: { title: 'Live Out Thy Life Within Me' },
    317: { title: 'Lead Me to Calvary' },
    318: { title: 'Whiter Than Snow' },
    319: { title: 'Lord, I Want to Be a Christian' },
    320: { title: 'Lord of Creation' },
    321: { title: 'My Jesus, I Love Thee' },
    322: { title: 'Nothing Between' },
    323: { title: 'O for a Heart to Praise My God!' },
    324: { title: 'Just as I Am, Thine Own to Be' },
    325: { title: 'Jesus, I My Cross Have Taken' },
    326: { title: 'Open My Eyes That I May See' },
    327: { title: 'I’d Rather Have Jesus' },
    328: { title: 'Must Jesus Bear the Cross Alone' },
    329: { title: 'Take the World, but Give Me Jesus' },
    330: { title: 'Take My Life and Let It Be' },
    331: { title: 'O Jesus, I Have Promised' },
    332: { title: 'The Cleansing Wave' },
    333: {
      title: 'On Jordan’s Banks the Baptist’s Cry',
      scriptureReference: 'Luke 3:2-4',
    },
    334: { title: 'Come, Thou Fount of Every Blessing' },
    335: { title: 'What a Wonderful Savior' },
    336: { title: 'There Is a Fountain' },
    337: { title: 'Redeemed!', scriptureReference: 'Lamentations 3:58' },
    338: { title: 'Redeemed!', scriptureReference: 'Lamentations 3:58' },
    339: { title: 'God Is My Strong Salvation', scriptureReference: 'Psalm 27:1-3' },
    340: { title: 'Jesus Saves' },
    341: { title: 'To God Be the Glory' },
    342: { title: 'Is This a Day of New Beginnings?' },
    343: { title: 'I Will Sing of My Redeemer' },
    344: { title: 'I Love Your Kingdom, Lord' },
    345: { title: 'Christ Is the World’s True Light' },
    346: { title: 'Lord, Who Dost Give to Thy Church' },
    347: { title: 'Built on the Rock' },
    348: { title: 'The Church Has One Foundation' },
    349: { title: 'God Is Love', scriptureReference: '1 John 4:7-8' },
    350: { title: 'Blest Be the Tie That Binds' },
    351: { title: 'Thy Hand, O God Has Guided', scriptureReference: 'Ephesians 4:5' },
    352: { title: 'This Is My Will' },
    353: { title: 'Father, Help Your People' },
    354: { title: 'Thy Love, O God' },
    355: { title: 'Where Cross the Crowded Ways of Life' },
    356: { title: 'All Who Love and Serve Your City' },
    357: { title: 'Come, Labor On' },
    358: { title: 'Far and Near the Fields Are Teeming' },
    359: { title: 'Hark! the Voice of Jesus Calling' },
    360: { title: 'From the Eastern Mountains', scriptureReference: 'Matthew 2:1-2' },
    361: { title: 'Hark! ‘Tis the Shepherd’s Voice I Hear' },
    362: { title: 'Lift High the Cross' },
    363: { title: 'Lord, Whose Love in Humble Service' },
    364: { title: 'O Jesus Christ, to You' },
    365: { title: 'O Zion, Haste' },
    366: { title: 'O Where Are the Reapers?' },
    367: { title: 'Rescue the Perishing' },
    368: { title: 'Watchman, Blow the Gospel Trumpet' },
    369: { title: 'Bringing in the Sheaves' },
    370: { title: 'Christ for the World' },
    371: { title: 'Lift Him Up' },
    372: { title: 'How Beauteous Are Their Feet', scriptureReference: 'Isaiah 52:7-9' },
    373: { title: 'Seeking the Lost' },
    374: { title: 'Jesus, With Thy Church Abide' },
    375: { title: 'Work, for the Night Is Coming' },
    376: { title: 'All Things Are Thine' },
    377: { title: 'Go Forth, Go Forth With Christ' },
    378: { title: 'Go, Preach My Gospel', scriptureReference: 'Mark 16:15-17' },
    379: { title: 'We Give This Child to You' },
    380: { title: 'Welcome, Day of Sweet Repose' },
    381: { title: 'Holy Sabbath Day of Rest' },
    382: { title: 'O Day of Rest and Gladness' },
    383: { title: 'O Day of Rest and Gladness' },
    384: { title: 'Safely Through Another Week' },
    385: { title: 'Crowning Jewel of Creation' },
    386: { title: 'The Sacred Anthem' },
    387: { title: 'Come, O Sabbath Day' },
    388: { title: 'Don’t Forget the Sabbath' },
    389: { title: 'Light of Light, Enlighten Me' },
    390: { title: 'We Love Thy Sabbath, Lord' },
    391: { title: 'Welcome, Welcome, Day of Rest' },
    392: { title: 'Dear Lord, We Come at Set of Sun' },
    393: { title: 'Lord of the Sabbath' },
    394: { title: 'Far From All Care' },
    395: { title: 'As Birds Unto the Genial Homeland' },
    396: { title: 'Lord God, Your Love Has Called Us Here' },
    397: { title: 'An Upper Room' },
    398: { title: 'Bread of the World' },
    399: { title: 'Beneath the Forms of Outward Rite', scriptureReference: 'Mark 14:15' },
    400: { title: 'I Come With Joy' },
    401: { title: 'In Imitation, Lord of Thee' },
    402: { title: 'By Christ Redeemed', scriptureReference: '1 Corinthians 11:23-26' },
    403: { title: 'Let Us Break Bread Together', scriptureReference: 'Malachi 4:2' },
    404: { title: 'Now Let Us From This Table Rise' },
    405: { title: 'O God, Unseen, Yet Ever Near' },
    406: { title: 'Love Consecrates the Humblest Act' },
    407: { title: 'Sent Forth by God’s Blessing' },
    408: { title: 'Lord, Enthroned in Heavenly Splendor' },
    409: { title: 'Jesus Invites His Saints' },
    410: { title: 'Thy Broken Body, Gracious Lord' },
    411: { title: 'The Son of God Proclaim' },
    412: { title: 'Cover With His Life' },
    413: { title: 'God Has Spoken by His Prophets', scriptureReference: 'Hebrews 1:1-2' },
    414: {
      title: 'Fruitful Trees, the Spirit’s Sowing',
      scriptureReference: 'Galatians 5:22-23',
    },
    415: {
      title: 'Christ the Lord, All Power Possessing',
      scriptureReference: 'Matthew 28:18-20',
    },
    416: { title: 'The Judgment Has Set' },
    417: { title: 'O Solemn Thought' },
    418: { title: 'Day of Judgment, Day of Wonders!' },
    419: { title: 'Soon Shall the Trump of God' },
    420: { title: 'Jerusalem, My Happy Home' },
    421: { title: 'For All the Saints' },
    422: { title: 'Marching to Zion' },
    423: { title: 'Glorious Things of Thee Are Spoken' },
    424: { title: 'For Thee, O Dear, Dear Country' },
    425: { title: 'Holy, Holy, Is What the Angels Sing' },
    426: { title: 'I Shall See the King' },
    427: { title: 'No Night There' },
    428: { title: 'Sweet By and By' },
    429: { title: 'Jerusalem the Golden' },
    430: { title: 'Joy By and By' },
    431: { title: 'Over Yonder' },
    432: { title: 'Shall We Gather at the River' },
    433: { title: 'Ten Thousand Times Ten Thousand' },
    434: { title: 'We Speak of the Realms' },
    435: { title: 'The Glory Song' },
    436: { title: 'The Homeland', scriptureReference: 'Revelation 21:4' },
    437: { title: 'I’m Going Home', scriptureReference: 'Revelation 21:4' },
    438: { title: 'You Will See Your Lord A-Coming' },
    439: { title: 'How Far From Home?' },
    440: { title: 'How Cheering Is the Christian’s Hope' },
    441: { title: 'I Saw One Weary', scriptureReference: 'Titus 2:13' },
    442: { title: 'How Sweet Are the Tidings' },
    443: { title: 'There’ll Be No Sorrow There', scriptureReference: 'Revelation 21:4' },
    444: { title: 'I’m a Pilgrim' },
    445: { title: 'I’m But a Stranger Here' },
    446: {
      title: 'Lo, What a Glorious Sight Appears',
      scriptureReference: 'Revelation 21:1-4',
    },
    447: { title: 'Long Upon the Mountains', scriptureReference: 'Ezekiel 34:12' },
    448: { title: 'O, When Shall I See Jesus' },
    449: { title: 'Never Part Again' },
    450: { title: 'Beautiful Zion' },
    451: { title: 'Together Let Us Sweetly Live' },
    452: { title: 'What Heavenly Music' },
    453: { title: 'We Have Heard' },
    454: { title: 'Don’t You See My Jesus Coming?' },
    455: { title: 'Immortal Love, Forever Full' },
    456: { title: 'My Lord and I' },
    457: { title: 'I Love to Tell the Story' },
    458: { title: 'More Love to Thee' },
    459: { title: 'As the Bridegroom to His Chosen' },
    460: { title: 'As Water to the Thirsty' },
    461: { title: 'Be Still, My Soul', scriptureReference: 'Psalm 46:10' },
    462: { title: 'Blessed Assurance, Jesus Is Mine!' },
    463: { title: 'Peace, Perfect Peace', scriptureReference: 'Isaiah 26:3' },
    464: { title: 'When I Can Read My Title Clear' },
    465: { title: 'I Heard the Voice of Jesus' },
    466: { title: 'Wonderful Peace' },
    467: { title: 'Life Is Great! So Sing About It' },
    468: { title: 'A Child of the King' },
    469: {
      title: 'Leaning on the Everlasting Arms',
      scriptureReference: 'Deuteronomy 33:27',
    },
    470: { title: 'There’s Sunshine in My Soul Today' },
    471: { title: 'Grant Us Your Peace' },
    472: { title: 'A Song of Heaven and Homeland' },
    473: { title: 'Nearer My God, to Thee', scriptureReference: 'Genesis 28:10-19' },
    474: { title: 'Take the Name of Jesus With You' },
    475: { title: 'Balm in Gilead' },
    476: { title: 'Burdens Are Lifted at Calvary' },
    477: { title: 'Come, Ye Disconsolate' },
    478: { title: 'Sweet Hour of Prayer' },
    479: { title: 'Tread Softly' },
    480: { title: 'Dear Lord and Father' },
    481: { title: 'Dear Lord and Father' },
    482: { title: 'Father, Lead Me Day by Day' },
    483: { title: 'I Need Thee Every Hour' },
    484: { title: 'I Need Thee, Precious Jesus' },
    485: { title: 'I Must Tell Jesus' },
    486: { title: 'I Do Believe' },
    487: { title: 'In the Garden', scriptureReference: 'John 20:15-17' },
    488: { title: 'At First I Prayed for Light' },
    489: { title: 'Jesus, Lover of My Soul' },
    490: { title: 'Jesus, Lover of My Soul' },
    491: { title: 'In the Hour of Trial' },
    492: { title: 'Like Jesus' },
    493: { title: 'Fill My Cup, Lord' },
    494: { title: 'We Would See Jesus', scriptureReference: 'John 12:21' },
    495: { title: 'Near the Heart of God' },
    496: { title: 'Eternal Love, We Have No Good', scriptureReference: 'Revelation 8:3' },
    497: { title: 'O Gracious Father of Mankind' },
    498: { title: 'Still, Still With Thee' },
    499: { title: 'What a Friend We Have in Jesus' },
    500: { title: 'Take Time to Be Holy', scriptureReference: '1 Peter 1:16' },
    501: { title: 'Tis the Blessed Hour of Prayer' },
    502: { title: 'Sun of My Soul' },
    503: { title: 'A Quiet Place' },
    504: { title: 'Lord Jesus, Think on Me' },
    505: { title: 'I Need the Prayers' },
    506: { title: 'A Mighty Fortress', scriptureReference: 'Psalm 46:1' },
    507: { title: 'Moment by Moment' },
    508: { title: 'Anywhere With Jesus' },
    509: { title: 'How Firm a Foundation' },
    510: {
      title: 'If You But Trust in God to Guide You',
      scriptureReference: 'Psalm 55:22',
    },
    511: { title: 'I Know Whom I Have Believed', scriptureReference: '2 Timothy 1:12' },
    512: { title: 'Just When I Need Him Most' },
    513: { title: 'In Heavenly Love Abiding', scriptureReference: 'Psalm 23' },
    514: { title: 'Lord of Our Life' },
    515: { title: 'The Lord Is My Light' },
    516: { title: 'All the Way' },
    517: { title: 'My Faith Looks Up to Thee' },
    518: { title: 'Standing on the Promises', scriptureReference: '2 Peter 1:4' },
    519: { title: 'Give to the Winds Your Fears', scriptureReference: 'Psalm 37:5' },
    520: { title: 'He Hideth My Soul' },
    521: { title: 'Depth of Mercy', scriptureReference: '1 Timothy 1:15' },
    522: { title: 'My Hope Is Built on Nothing Less' },
    523: { title: 'My Faith Has Found a Resting Place' },
    524: { title: 'Tis So Sweet to Trust in Jesus' },
    525: { title: 'Hiding in Thee', scriptureReference: 'Psalm 61:1-2' },
    526: { title: 'Because He Lives' },
    527: { title: 'From Every Stormy Wind', scriptureReference: 'Exodus 25:22' },
    528: { title: 'A Shelter in the Time of Storm' },
    529: { title: 'Under His Wings' },
    530: { title: 'It Is Well With My Soul' },
    531: { title: 'We’ll Build on the Rock', scriptureReference: 'Matthew 7:24-26' },
    532: { title: 'Day by Day', scriptureReference: 'Deuteronomy 33:25' },
    533: { title: 'O for a Faith' },
    534: { title: 'Will Your Anchor Hold?' },
    535: { title: 'I Am Trusting Thee, Lord Jesus', scriptureReference: 'Psalm 71:1' },
    536: { title: 'God, Who Stretched the Spangled Heavens' },
    537: { title: 'He Leadeth Me', scriptureReference: 'Psalm 23:2' },
    538: { title: 'Guide Me, O Thou Great Jehovah' },
    539: { title: 'I Will Early Seek the Savior' },
    540: { title: 'Gentle Jesus, Meek and Mild' },
    541: { title: 'Lord, Speak to Me', scriptureReference: 'Romans 14:7' },
    542: { title: 'Jesus, Friend So Kind' },
    543: { title: 'Jesus, Friend of Little Children' },
    544: { title: 'Jesus, Son of Blessed Mary' },
    545: { title: 'Savior, Like a Shepherd' },
    546: { title: 'The Lord’s My Shepherd', scriptureReference: 'Psalm 23' },
    547: { title: 'Be Thou My Vision' },
    548: { title: 'Now Praise the Hidden God of Love' },
    549: { title: 'Loving Shepherd of Thy Sheep', scriptureReference: 'John 10:27-28' },
    550: { title: 'Every Flower That Grows' },
    551: { title: 'Jesus, Savior, Pilot Me' },
    552: { title: 'The Lord’s My Shepherd', scriptureReference: 'Psalm 23' },
    553: { title: 'Jesus, Guide Our Way' },
    554: { title: 'O Let Me Walk With Thee' },
    555: { title: 'Shepherd of Tender Youth', scriptureReference: 'Deuteronomy 32:7' },
    556: { title: 'As Saints of Old' },
    557: { title: 'Come, Ye Thankful People' },
    558: { title: 'For the Fruits of His Creation' },
    559: { title: 'Now Thank We All Our God' },
    560: { title: 'Let All Things Now Living', scriptureReference: '1 Chronicles 16:32' },
    561: { title: 'We Plow the Fields' },
    562: { title: 'Come, Sing a Song of Harvest' },
    563: { title: 'Praise and Thanksgiving' },
    564: { title: 'For Sunrise Hope and Sunset Calm' },
    565: { title: 'For the Beauty of the Earth' },
    566: { title: 'Father, We Thank You' },
    567: { title: 'Have Thine Own Way, Lord' },
    568: { title: 'Make Me a Captive, Lord' },
    569: { title: 'Pass Me Not, O Gentle Savior' },
    570: { title: 'Not I, but Christ' },
    571: { title: 'What Does the Lord Require?', scriptureReference: 'Micah 6:8' },
    572: { title: 'Give of Your Best to the Master' },
    573: { title: 'I’ll Go Where You Want Me to Go' },
    574: { title: 'O Master, Let Me Walk With Thee' },
    575: { title: 'Let Your Heart Be Broken' },
    576: { title: 'Awake, Awake to Love and Work' },
    577: { title: 'In the Heart of Jesus' },
    578: { title: 'So Send I You', scriptureReference: 'John 20:21' },
    579: { title: 'Tis Love That Makes Us Happy' },
    580: { title: 'This Little Light of Mine' },
    581: { title: 'When the Church of Jesus' },
    582: { title: 'Working, O Christ, With Thee' },
    583: { title: 'You That Know the Lord', scriptureReference: '1 Peter 2:4-10' },
    584: { title: 'There’s a Spirit in the Air' },
    585: { title: 'When Christ Was Lifted From the Earth' },
    586: { title: 'What Joy It Is to Worship Here' },
    587: { title: 'In Christ There Is No East nor West' },
    588: { title: 'Lord of All Nations', scriptureReference: 'Acts 10:34-35' },
    589: { title: 'Holy Spirit, Gracious Guest', scriptureReference: '1 Corinthians 13' },
    590: { title: 'Trust and Obey' },
    591: { title: 'In Our Work and In Our Play' },
    592: {
      title: 'Watchman, Tell Us of the Night',
      scriptureReference: 'Isaiah 21:11-12',
    },
    593: { title: 'In Times Like These' },
    594: { title: 'Heir of the Kingdom' },
    595: { title: 'Let Every Lamp' },
    596: { title: 'Look for the Waymarks', scriptureReference: 'Daniel 2:31-44' },
    597: { title: 'Ye Servants of the Lord' },
    598: { title: 'Watch, Ye Saints' },
    599: { title: 'Rejoice, Rejoice, Believers', scriptureReference: 'Matthew 25:1-7' },
    600: { title: 'Hold Fast Till I Come' },
    601: { title: 'Watchmen, on the Walls of Zion' },
    602: { title: 'O Brother, Be Faithful' },
    603: { title: 'Christian, Seek Not Repose', scriptureReference: 'Matthew 26:41' },
    604: { title: 'We Know Not the Hour', scriptureReference: 'Matthew 24:36-42' },
    605: { title: 'My Soul, Be on Thy Guard' },
    606: { title: 'Once to Every Man and Nation' },
    607: { title: 'God of Grace and God of Glory' },
    608: { title: 'Faith Is the Victory' },
    609: { title: 'Am I a Soldier of the Cross?' },
    610: { title: 'Stand Like the Brave' },
    611: { title: 'Awake, My Soul!', scriptureReference: 'Philippians 3:14' },
    612: { title: 'Onward, Christian Soldiers!' },
    613: { title: 'Fight the Good Fight', scriptureReference: '1 Timothy 6:12' },
    614: { title: 'Sound the Battle Cry' },
    615: { title: 'Rise Up, O Church of God' },
    616: { title: 'Soldiers of Christ, Arise', scriptureReference: 'Ephesians 6:13' },
    617: { title: 'We Are Living, We Are Dwelling' },
    618: { title: 'Stand Up! Stand Up for Jesus!', scriptureReference: 'Ephesians 6:14' },
    619: { title: 'Lead On, O King Eternal' },
    620: { title: 'On Jordan’s Stormy Banks' },
    621: { title: 'Gracious Father, Guard Thy Children' },
    622: { title: 'Come, Come, Ye Saints' },
    623: { title: 'I Will Follow Thee' },
    624: { title: 'I Want Jesus to Walk With Me' },
    625: { title: 'Higher Ground' },
    626: { title: 'In a Little While We’re Going Home' },
    627: { title: 'Jacob’s Ladder' },
    628: { title: 'As Jacob With Travel Was Weary', scriptureReference: 'Genesis 28:12' },
    629: { title: 'O Happy Band of Pilgrims', scriptureReference: '1 Peter 1:6-7' },
    630: { title: 'Rise, My Soul, and Stretch Thy Wings' },
    631: { title: 'When on Life a Darkness Falls' },
    632: { title: 'Until Then' },
    633: { title: 'When We All Get to Heaven' },
    634: { title: 'Come, All Christians, Be Committed' },
    635: { title: 'Lord of All Good' },
    636: { title: 'God, Whose Giving Knows No Ending' },
    637: { title: 'Son of God, Eternal Savior' },
    638: { title: 'The Wise May Bring Their Learning' },
    639: { title: 'A Diligent and Grateful Heart' },
    640: { title: 'For Beauty of Meadows' },
    641: { title: 'God in His Love for Us' },
    642: { title: 'We Praise Thee With Our Minds' },
    643: { title: 'Father, Who on Us Do Shower' },
    644: { title: 'O God, Whose Will Is Life and Good' },
    645: { title: 'God of Our Fathers' },
    646: { title: 'To the Name That Brings Salvation' },
    647: { title: 'Mine Eyes Have Seen the Glory' },
    648: { title: 'I Vow to Thee, My Country' },
    649: { title: 'Lord, While for All Mankind' },
    650: { title: 'Our Father, by Whose Name' },
    651: { title: 'Happy the Home That Welcomes You' },
    652: { title: 'Love at Home' },
    653: { title: 'Lead Them, My God, to Thee' },
    654: { title: 'Lord, Bless Our Homes' },
    655: { title: 'Happy the Home' },
    656: { title: 'O Perfect Love' },
    657: { title: 'O God, From Whom Mankind' },
    658: { title: 'Heavenly Father, Hear Our Prayer' },
    659: { title: 'May the Grace of Christ Our Savior' },
    660: { title: 'Glory Be to the Father' },
    661: { title: 'Holy, Holy, Holy' },
    662: { title: 'Let All Mortal Flesh Keep Silence' },
    663: { title: 'Amens' },
    664: { title: 'Sevenfold Amen' },
    665: { title: 'All Things Come of Thee' },
    666: { title: 'Cast Thy Burden Upon the Lord', scriptureReference: 'Psalm 55:22' },
    667: { title: 'Lord, Bless Thy Word to Every Heart' },
    668: { title: 'O Thou Who Hearest' },
    669: {
      title: 'The Lord Bless You and Keep You',
      scriptureReference: 'Numbers 6:24-26',
    },
    670: { title: 'We Give Thee But Thine Own' },
    671: { title: 'As We Come to You in Prayer' },
    672: { title: 'Spirit of the Living God' },
    673: { title: 'May God Be With You' },
    674: { title: 'Shalom' },
    675: { title: 'May the Lord Bless and Keep You' },
    676: { title: 'Thy Word Is a Lantern' },
    677: { title: 'Heavenly Father, to Thee We Pray' },
    678: { title: 'God Be in My Head (Davies)' },
    679: { title: 'God Be in My Head (Coombs)' },
    680: { title: 'Holy Spirit, Hear Us' },
    681: { title: 'This Is the Day the Lord Hath Made' },
    682: { title: 'As You Have Promised, Lord', scriptureReference: 'Luke 2:29-32' },
    683: { title: 'Jesus, Stand Among Us', scriptureReference: 'John 20:19' },
    684: { title: 'Hear Our Prayer, O Lord' },
    685: { title: 'Cause Me to Hear' },
    686: { title: 'Bless Thou the Gifts' },
    687: {
      title: 'The Lord Is in His Holy Temple (Beltz)',
      scriptureReference: 'Habakkuk 2:20',
    },
    688: { title: 'Surely, Surely' },
    689: { title: 'Day by Day, Dear Lord' },
    690: { title: 'Dismiss Us, Lord, With Blessing' },
    691: { title: 'Lead Me, Lord', scriptureReference: 'Psalm 5:8' },
    692: {
      title: 'The Lord Is in His Holy Temple (Root)',
      scriptureReference: 'Habakkuk 2:20',
    },
    693: { title: 'Almighty Father', scriptureReference: 'Isaiah 30:18' },
    694: {
      title: 'Praise God, From Whom All Blessings',
      scriptureReference: 'Psalm 148:1-2',
    },
  },
};
