/**
 * SDA Hymnal 1985 Edition - English Hymn Metadata
 *
 * This file contains a structured JSON/TypeScript dictionary of metadata for the
 * Seventh-day Adventist Hymnal (1985 edition), mapping sequential indices to titles
 * and factual reference points for application logic and lookup features.
 *
 * LEGAL COMPLIANCE & REPOSITORY HOSTING NOTE:
 * This dataset consists strictly of non-copyrightable metadata and factual listings
 * (sequential numbers, brief titles, and historical scripture mappings). Under U.S.
 * Copyright Law (U.S. Copyright Office FAQ / Circular 34), short phrases, titles, and
 * mechanical numbering systems lack the creative authorship required for copyright.
 * See: https://www.copyright.gov/help/faq/faq-register.html
 *
 * Furthermore, in Feist Publications, Inc. v. Rural Telephone Service Co., 499 U.S. 340 (1991),
 * the U.S. Supreme Court ruled that factual compilations and historical cross-references
 * are not eligible for copyright protection, rejecting the "sweat of the brow" doctrine.
 *
 * Because this file contains only open factual schema and operational application flags—and
 * explicitly omits protected creative works such as modern musical notation, unique arrangements,
 * or proprietary lyric texts—it constitutes public factual data eligible for open distribution,
 * version control, and public hosting on platforms like GitHub.
 *
 * Data schema structured based on Hymnary index: https://hymnary.org/hymnal/SDAH1985
 *
 * Points directly to the official 1985 SDA index handled by Hymnary.
 * This is a 100% safe, legal redirect structure.
 *
 * "Yes, you may link directly from your app to our index of the SDAH hymnal on our website.
 * However, we are not able to make the copyrighted material in the hymnal available."
 * Dianne Shapiro, Hymnary.org, Calvin University, 2026-05-18 over email.
 *
 * The following is a legal disclaimer from this volunteer app developer to further clarify implementation
 * to reduce legal liability risk and ensure compliance with copyright policy:
 *
 * For certain hymns (e.g. Hymn #22) Hymnary.org will prompt the user to accept copyright terms
 * to view the content. This is a legal requirement and is not a bug in the app.
 * Do NOT attempt to scrape or store the content of Hymnary.org in this app, as it is copyrighted material.
 * Do NOT attempt to bypass the copyright terms prompt, as it is a legal requirement and is not a bug in the app.
 * For example, you may not directly link to the scanned image of the hymn on Hymnary servers.
 * You may only link to the official Hymnary.org page for the hymn.
 */

import { openURL } from './ExternalLinks';

export const openHymnal = (hymnNumber?: string | number) => {
  const hId =
    typeof hymnNumber === 'string' || typeof hymnNumber === 'number' ? hymnNumber : '';

  return openURL(`https://hymnary.org/hymn/SDAH1985/${hId}`);
};

export interface HymnEntry {
  title: string;
  /**
   * Indicates if the hymn has text-only lyrics or a page scan available.
   */
  hasLyricsOrScan?: boolean;
  /**
   * A primary scripture passage associated with the hymn's theme or lyrics.
   */
  scriptureReference?: string;
  /**
   * Cross-references to other hymnals.
   * Since the Chinese hymnal is a different book, we map the ID here.
   */
  mappings?: {
    zh?: number; // ID in the Chinese Hymnal
  };
}

/**
 * Represents a hymn entry with its number included,
 * used primarily for UI components and lists.
 */
export interface HydratedHymn extends HymnEntry {
  number: number;
}

export interface SDAHymnalData {
  // We use a Record where the key is the hymn number for O(1) lookups
  en: Record<number, HymnEntry>;
  // Add other languages here if supported in the future
}

/**
 * Converts the Record-based hymnal data into a sorted array.
 * This is the preferred way to "fetch" data for FlatLists or search screens.
 */
export const getSortedHymns = (lang: keyof SDAHymnalData = 'en'): HydratedHymn[] => {
  return Object.entries(SDA_HYMNAL_1985[lang])
    .map(([num, data]) => ({
      number: parseInt(num, 10),
      ...data,
    }))
    .sort((a, b) => a.number - b.number);
};

export const SDA_HYMNAL_1985: SDAHymnalData = {
  en: {
    1: {
      title: 'Praise to the Lord',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 103:2-5',
    },
    2: { title: 'All Creatures of Our God and King', hasLyricsOrScan: true },
    3: { title: 'God Himself Is With Us', hasLyricsOrScan: true },
    4: {
      title: 'Immortal, Invisible, God Only Wise',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 103',
    },
    5: { title: 'The Lord in Zion Reigneth', hasLyricsOrScan: true },
    6: { title: 'Holy, Holy, Holy', hasLyricsOrScan: true },
    7: { title: 'O Worship the King', hasLyricsOrScan: true },
    8: { title: 'The Lord Is in His Holy Temple', hasLyricsOrScan: true },
    9: { title: 'Come, Thou Almighty King', hasLyricsOrScan: true },
    10: { title: 'God the Father, We Adore Thee', hasLyricsOrScan: true },
    11: {
      title: 'The God of Abraham Praise',
      hasLyricsOrScan: true,
      scriptureReference: 'Exodus 3:14-15',
    },
    12: { title: 'O Sing a New Song to the Lord', hasLyricsOrScan: true },
    13: {
      title: 'Sing Praise to God Who Reigns Above',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 98',
    },
    14: { title: 'Let us praise the name of the Lord!' },
    15: { title: 'The Heavens Declare', hasLyricsOrScan: true },
    16: {
      title: 'The Spacious Firmament',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 100',
    },
    17: { title: 'Lord of the Bounds of Earth', hasLyricsOrScan: true },
    18: { title: 'God Is Our Song', hasLyricsOrScan: true },
    19: {
      title: 'The Earth Is the Lord’s',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 98',
    },
    20: {
      title: 'All Things Bright and Beautiful',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 150',
    },
    21: {
      title: 'Fairest Lord Jesus',
      hasLyricsOrScan: true,
      scriptureReference: '1 Timothy 1:17',
    },
    22: {
      title: 'Let All Things Now Living',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 118:14',
    },
    23: { title: 'Now the joyful bells a-ringing', scriptureReference: 'Psalm 148:9' },
    24: { title: 'The Wonder of It All', hasLyricsOrScan: true },
    25: {
      title: 'We Plow the Fields',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 150',
    },
    26: {
      title: 'Summer Suns Are Glowing',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 148',
    },
    27: {
      title: 'For the Beauty of the Earth',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 20:5',
    },
    28: { title: 'Praise we the Lord, who made all beauty' },
    29: { title: 'Praise God, From Whom All Blessings Flow', hasLyricsOrScan: true },
    30: { title: 'For the Fruits of His Creation', hasLyricsOrScan: true },
    31: { title: 'Come, Ye Thankful People, Come', hasLyricsOrScan: true },
    32: { title: 'Now Thank We All Our God', hasLyricsOrScan: true },
    33: {
      title: 'I Sing the Mighty Power of God',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 98',
    },
    34: { title: 'O Love of God, How Strong and True!', hasLyricsOrScan: true },
    35: { title: 'God Is Love', hasLyricsOrScan: true, scriptureReference: 'Psalm 147' },
    36: { title: 'O God, Our Help in Ages Past', hasLyricsOrScan: true },
    37: {
      title: 'Beneath the Cross of Jesus',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 34',
    },
    38: { title: 'A Mighty Fortress Is Our God', hasLyricsOrScan: true },
    39: {
      title: 'Lead Us, Heavenly Father',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 5',
    },
    40: { title: 'The Lord’s My Shepherd', hasLyricsOrScan: true },
    41: {
      title: 'How Great Thou Art',
      hasLyricsOrScan: true,
      scriptureReference: 'Hebrews 1:3',
    },
    42: { title: 'O Lord, My God, When I in Awesome Wonder', hasLyricsOrScan: true },
    43: {
      title: 'Eternal Father, Strong to Save',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 150:6',
    },
    44: { title: 'Morning has broken, Like the first morning' },
    45: { title: 'Great Is Thy Faithfulness', hasLyricsOrScan: true },
    46: { title: 'Amazing Grace', hasLyricsOrScan: true },
    47: { title: 'Marvelous Grace', hasLyricsOrScan: true },
    48: { title: 'Grace Greater Than Our Sin', hasLyricsOrScan: true },
    49: { title: 'The Love of God', hasLyricsOrScan: true },
    50: { title: 'Love Divine', hasLyricsOrScan: true, scriptureReference: 'Luke 24:29' },
    51: { title: 'Tell Me the Story of Jesus', hasLyricsOrScan: true },
    52: { title: 'I Love to Tell the Story', hasLyricsOrScan: true },
    53: {
      title: 'Jesus Loves Me',
      hasLyricsOrScan: true,
      scriptureReference: 'Mark 10:14',
    },
    54: { title: 'There Is a Fountain', hasLyricsOrScan: true },
    55: { title: 'The Old Rugged Cross', hasLyricsOrScan: true },
    56: { title: 'When I Survey the Wondrous Cross', hasLyricsOrScan: true },
    57: {
      title: 'Wondrous Love',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 3:5',
    },
    58: { title: 'At the Cross', hasLyricsOrScan: true },
    59: { title: 'Jesus Paid It All', hasLyricsOrScan: true },
    60: { title: 'There Is a Green Hill Far Away', hasLyricsOrScan: true },
    61: { title: 'Ah, Holy Jesus!', hasLyricsOrScan: true },
    62: {
      title: 'Go to Dark Gethsemane',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 84',
    },
    63: {
      title: 'Ride On in Majesty',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 95:1-6',
    },
    64: { title: 'All Glory, Laud, and Honor', hasLyricsOrScan: true },
    65: {
      title: 'Hosanna, Loud Hosanna',
      hasLyricsOrScan: true,
      scriptureReference: '2 Corinthians 13:11',
    },
    66: { title: 'When Morning Gilds the Skies', hasLyricsOrScan: true },
    67: { title: 'Christ the Lord Is Risen Today', scriptureReference: 'Luke 2:29-32' },
    68: {
      title: 'Look, Ye Saints! The Sight Is Glorious',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 1:7',
    },
    69: { title: 'Crown Him With Many Crowns', hasLyricsOrScan: true },
    70: {
      title: 'All Hail the Power of Jesus’ Name!',
      hasLyricsOrScan: true,
      scriptureReference: '2 Corinthians 13:14',
    },
    71: { title: 'The Head That Once Was Crowned With Thorns', hasLyricsOrScan: true },
    72: { title: 'Jesus, Name Above All Names', hasLyricsOrScan: true },
    73: {
      title: 'Before the Throne of God Above',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 4:8-11',
    },
    74: {
      title: 'Jesus, What a Friend for Sinners!',
      hasLyricsOrScan: true,
      scriptureReference: 'Isaiah 48:11',
    },
    75: { title: "There's the wonder of sunset at evening" },
    76: { title: 'The Great Physician', hasLyricsOrScan: true },
    77: { title: 'O How I Love Jesus', hasLyricsOrScan: true },
    78: { title: 'Jesus, Lover of My Soul', hasLyricsOrScan: true },
    79: { title: 'Jesus, Priceless Treasure', hasLyricsOrScan: true },
    80: { title: 'O world of God, so vast and strange' },
    81: { title: 'Though I speak with tongues of men and angels' },
    82: {
      title: 'What Child Is This?',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 100',
    },
    83: {
      title: 'The First Noel',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 104',
    },
    84: { title: 'Hark! The Herald Angels Sing', hasLyricsOrScan: true },
    85: { title: 'Silent Night, Holy Night', hasLyricsOrScan: true },
    86: { title: 'O Come, All Ye Faithful', hasLyricsOrScan: true },
    87: { title: 'Joy to the World', hasLyricsOrScan: true },
    88: {
      title: 'O Little Town of Bethlehem',
      hasLyricsOrScan: true,
      scriptureReference: 'Genesis 1',
    },
    89: {
      title: 'Away in a Manger',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 96',
    },
    90: { title: 'As With Gladness Men of Old', hasLyricsOrScan: true },
    91: { title: 'We Three Kings', hasLyricsOrScan: true },
    92: { title: 'There’s a Song in the Air', hasLyricsOrScan: true },
    93: { title: 'Angels From the Realms of Glory', hasLyricsOrScan: true },
    94: { title: 'It Came Upon the Midnight Clear', hasLyricsOrScan: true },
    95: { title: 'Spring has now unwrapped the flowers' },
    96: {
      title: 'Thou Didst Leave Thy Throne',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 19',
    },
    97: { title: 'Lord of the boundless curves of space' },
    98: { title: 'Come, Thou Long-Expected Jesus', hasLyricsOrScan: true },
    99: {
      title: 'All Things Bright and Beautiful',
      hasLyricsOrScan: true,
      scriptureReference: '1 Peter 5:7',
    },
    100: {
      title: 'Great Is Thy Faithfulness',
      hasLyricsOrScan: true,
      scriptureReference: 'Lamentations 3:22-23',
    },
    101: { title: 'Children of the Heavenly Father', hasLyricsOrScan: true },
    102: {
      title: 'Unto the Hills',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 121',
    },
    103: {
      title: 'O God, Our Help',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 90',
    },
    104: {
      title: 'My Shepherd Will Supply my Need',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 23',
    },
    105: { title: 'Sing to the Great Jehovah’s Praise', hasLyricsOrScan: true },
    106: { title: 'Give to Our God Immortal Praise', hasLyricsOrScan: true },
    107: {
      title: 'God Moves in a Mysterious Way',
      hasLyricsOrScan: true,
      scriptureReference: 'John 13:7',
    },
    108: {
      title: 'Amazing Grace',
      hasLyricsOrScan: true,
      scriptureReference: '1 Chronicles 17:16-17',
    },
    109: { title: 'Marvelous Grace', hasLyricsOrScan: true },
    110: {
      title: 'God’s Free Mercy Streameth',
      hasLyricsOrScan: true,
      scriptureReference: 'Ecclesiastes 11:7',
    },
    111: { title: 'It Took a Miracle', hasLyricsOrScan: true },
    112: { title: 'Let Us With a Gladsome Mind', hasLyricsOrScan: true },
    113: {
      title: 'As Pants the Hart',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 42:1-5',
    },
    114: { title: 'There’s a Wideness', hasLyricsOrScan: true },
    115: { title: 'O Come, O Come, Immanuel', hasLyricsOrScan: true },
    116: { title: 'Of the Father’s Love Begotten', hasLyricsOrScan: true },
    117: { title: 'The Advent of Our God', hasLyricsOrScan: true },
    118: { title: 'The First Noel', hasLyricsOrScan: true },
    119: { title: 'Angels From the Realms of Glory', hasLyricsOrScan: true },
    120: { title: 'There’s a Song in the Air', hasLyricsOrScan: true },
    121: { title: 'Go, Tell It on the Mountain', hasLyricsOrScan: true },
    122: {
      title: 'Hark! the Herald Angels Sing',
      hasLyricsOrScan: true,
      scriptureReference: 'Luke 2:14',
    },
    123: {
      title: 'As With Gladness Men of Old',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 2:1-11',
    },
    124: { title: 'Away in a Manger', hasLyricsOrScan: true },
    125: {
      title: 'Joy to the World',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 98:4-9',
    },
    126: { title: 'In the Bleak Midwinter', hasLyricsOrScan: true },
    127: {
      title: 'Infant Holy, Infant Lowly',
      hasLyricsOrScan: true,
      scriptureReference: 'Luke 2:7-11',
    },
    128: { title: 'Break forth, O beauteous heavenly light' },
    129: { title: 'As it fell upon a night In the winter weather' },
    130: {
      title: 'It Came Upon the Midnight Clear',
      hasLyricsOrScan: true,
      scriptureReference: 'Luke 2:13-14',
    },
    131: { title: 'Lo, How a Rose E’er Blooming', hasLyricsOrScan: true },
    132: { title: 'O Come, All Ye Faithful', hasLyricsOrScan: true },
    133: { title: 'Now Is Born the Divine Christ Child', hasLyricsOrScan: true },
    134: { title: 'O Jesus sweet, O Jesus mild' },
    135: {
      title: 'O Little Town of Bethlehem',
      hasLyricsOrScan: true,
      scriptureReference: 'Luke 2:13-14',
    },
    136: { title: 'Good Christians, Now Rejoice', hasLyricsOrScan: true },
    137: { title: 'We Three Kings', hasLyricsOrScan: true },
    138: { title: 'Rise Up, Shepherd, and Follow', hasLyricsOrScan: true },
    139: {
      title: 'While Shepherds Watched Their Flocks',
      hasLyricsOrScan: true,
      scriptureReference: 'Luke 2:8-14',
    },
    140: { title: 'Thou Didst Leave Thy Throne', hasLyricsOrScan: true },
    141: { title: 'What Child Is This?', hasLyricsOrScan: true },
    142: { title: 'Angels we have heard on high', scriptureReference: 'Luke 2:13-17' },
    143: { title: 'Silent Night, Holy Night', hasLyricsOrScan: true },
    144: { title: 'O Sing a Song of Bethlehem', hasLyricsOrScan: true },
    145: { title: 'Songs of Thankfulness and Praise', hasLyricsOrScan: true },
    146: {
      title: 'I Think When I Read That Sweet Story',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 19:14-15',
    },
    147: {
      title: 'Christ Upon the Mountain Peak',
      hasLyricsOrScan: true,
      scriptureReference: 'Mark 9:2-7',
    },
    148: { title: 'O Love, How Deep, How Broad', hasLyricsOrScan: true },
    149: { title: 'Once in Royal David’s City', hasLyricsOrScan: true },
    150: { title: 'Who Is He in Yonder Stall?', hasLyricsOrScan: true },
    151: { title: 'Jesus Walked This Lonesome Valley', hasLyricsOrScan: true },
    152: { title: 'Tell Me the Story of Jesus', hasLyricsOrScan: true },
    153: { title: 'Prince of Peace, Control My Will', hasLyricsOrScan: true },
    154: {
      title: 'When I Survey the Wondrous Cross 4/4',
      hasLyricsOrScan: true,
      scriptureReference: 'Galatians 6:14',
    },
    155: {
      title: 'When I Survey the Wondrous Cross 3/4',
      hasLyricsOrScan: true,
      scriptureReference: 'Galatians 6:14',
    },
    156: { title: 'O Sacred Head Now Wounded', hasLyricsOrScan: true },
    157: { title: 'Go to Dark Gethsemane', hasLyricsOrScan: true },
    158: { title: 'Were You There?', hasLyricsOrScan: true },
    159: { title: 'The Old Rugged Cross', hasLyricsOrScan: true },
    160: { title: 'Ride On in Majesty', hasLyricsOrScan: true },
    161: {
      title: 'Throned Upon the Awful Tree',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 27:45-46',
    },
    162: { title: 'Wondrous Love', hasLyricsOrScan: true },
    163: { title: 'At the Cross', hasLyricsOrScan: true },
    164: { title: 'There Is a Green Hill Far Away', hasLyricsOrScan: true },
    165: {
      title: 'Look, You Saints! the Sight Is Glorious',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 11:15',
    },
    166: { title: 'Christ the Lord Is Risen Today', hasLyricsOrScan: true },
    167: { title: 'Alleluia! Sing to Jesus', hasLyricsOrScan: true },
    168: { title: 'And have the bright immensities' },
    169: { title: 'Come, You Faithful', hasLyricsOrScan: true },
    170: { title: 'Come, You Faithful', hasLyricsOrScan: true },
    171: { title: 'Thine Is the Glory', hasLyricsOrScan: true },
    172: { title: 'The Strife Is O’er', hasLyricsOrScan: true },
    173: { title: 'Good Christian Friends, Rejoice!', hasLyricsOrScan: true },
    174: {
      title: 'Star of Our Hope',
      hasLyricsOrScan: true,
      scriptureReference: '1 Thessalonians 4:16-17',
    },
    175: { title: 'Now the Green Blade Rises', hasLyricsOrScan: true },
    176: { title: 'Hail the Day That Sees Him Rise', hasLyricsOrScan: true },
    177: { title: 'Jesus, Your Blood and Righteousness', hasLyricsOrScan: true },
    178: {
      title: 'The Unveiled Christ',
      hasLyricsOrScan: true,
      scriptureReference: 'Mark 15:37-38',
    },
    179: {
      title: 'The Wonders of Redeeming Love',
      hasLyricsOrScan: true,
      scriptureReference: 'Hebrews 4:14-16',
    },
    180: { title: 'O Listen to Our Wondrous Story', hasLyricsOrScan: true },
    181: {
      title: 'Does Jesus Care?',
      hasLyricsOrScan: true,
      scriptureReference: '1 Peter 5:7',
    },
    182: { title: 'Christ Is Alive', hasLyricsOrScan: true },
    183: { title: 'I Will Sing of Jesus’ Love', hasLyricsOrScan: true },
    184: { title: 'Jesus Paid It All', hasLyricsOrScan: true },
    185: { title: 'Jesus Is All the World to Me', hasLyricsOrScan: true },
    186: { title: 'I’ve Found a Friend', hasLyricsOrScan: true },
    187: { title: 'Jesus, What a Friend for Sinners', hasLyricsOrScan: true },
    188: { title: 'My Song Is Love Unknown', hasLyricsOrScan: true },
    189: { title: 'All That Thrills My Soul', hasLyricsOrScan: true },
    190: {
      title: 'Jesus Loves Me',
      hasLyricsOrScan: true,
      scriptureReference: 'Proverbs 8:17',
    },
    191: { title: 'Love Divine', hasLyricsOrScan: true },
    192: { title: 'O Shepherd divine, I know Thou art mine' },
    193: { title: 'Savior, Teach Me', hasLyricsOrScan: true },
    194: { title: 'Sing We of the Modern City', hasLyricsOrScan: true },
    195: {
      title: 'Showers of Blessing',
      hasLyricsOrScan: true,
      scriptureReference: 'Ezekiel 34:26',
    },
    196: { title: 'Tell Me the Old, Old Story', hasLyricsOrScan: true },
    197: {
      title: 'The King of Love My Shepherd Is',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 23',
    },
    198: { title: 'And Can It Be?', hasLyricsOrScan: true },
    199: { title: 'The Head That Once Was Crowned', hasLyricsOrScan: true },
    200: {
      title: 'The Lord Is Coming',
      hasLyricsOrScan: true,
      scriptureReference: '1 Corinthians 16:22',
    },
    201: { title: 'Christ Is Coming', hasLyricsOrScan: true },
    202: { title: 'Hail Him the King of Glory', hasLyricsOrScan: true },
    203: { title: 'This Is the Threefold Truth', hasLyricsOrScan: true },
    204: { title: 'Come, Thou Long Expected Jesus', hasLyricsOrScan: true },
    205: { title: 'Gleams of the Golden Morning', hasLyricsOrScan: true },
    206: { title: 'Face to Face', hasLyricsOrScan: true },
    207: {
      title: 'It May Be at Morn',
      hasLyricsOrScan: true,
      scriptureReference: 'Mark 13:35',
    },
    208: { title: 'There’ll Be No Dark Valley', hasLyricsOrScan: true },
    209: { title: 'That Glorious Day Is Coming', hasLyricsOrScan: true },
    210: {
      title: 'Wake, Awake, for Night Is Flying',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 25:6-7',
    },
    211: {
      title: 'Lo! He Comes',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 1:7',
    },
    212: { title: '‘Tis Almost Time for the Lord to Come', hasLyricsOrScan: true },
    213: { title: 'Jesus Is Coming Again', hasLyricsOrScan: true },
    214: { title: 'We Have This Hope' },
    215: { title: 'The King Shall Come', hasLyricsOrScan: true },
    216: { title: 'When the Roll Is Called Up Yonder', hasLyricsOrScan: true },
    217: { title: 'The Church Has Waited Long', hasLyricsOrScan: true },
    218: {
      title: 'When He Cometh',
      hasLyricsOrScan: true,
      scriptureReference: 'Malachi 3:17',
    },
    219: { title: 'When Jesus Comes in Glory', hasLyricsOrScan: true },
    220: {
      title: 'When He Comes',
      hasLyricsOrScan: true,
      scriptureReference: '1 Thessalonians 4:14-17',
    },
    221: {
      title: 'Rejoice, the Lord Is King',
      hasLyricsOrScan: true,
      scriptureReference: 'Philippians 4:4',
    },
    222: { title: 'Hark! Ten Thousand Harps and Voices', hasLyricsOrScan: true },
    223: {
      title: 'Crown Him With Many Crowns',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 19:12',
    },
    224: { title: 'Seek Ye First the Kingdom' },
    225: {
      title: 'God Is Working His Purpose Out',
      hasLyricsOrScan: true,
      scriptureReference: 'Habakkuk 2:14',
    },
    226: { title: 'Lift Up Your Heads', hasLyricsOrScan: true },
    227: {
      title: 'Jesus Shall Reign',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 72:8-19',
    },
    228: { title: 'A Hymn of Glory Let Us Sing' },
    229: { title: 'All Hail the Power of Jesus’ Name', hasLyricsOrScan: true },
    230: {
      title: 'All Glory, Laud, and Honor',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 21:8-9',
    },
    231: {
      title: 'Blest Be the King',
      hasLyricsOrScan: true,
      scriptureReference: 'Mark 11:9-10',
    },
    232: {
      title: 'At the Name of Jesus',
      hasLyricsOrScan: true,
      scriptureReference: 'Philippians 2:8-11',
    },
    233: { title: 'Christ, Whose Glory Fills the Skies', hasLyricsOrScan: true },
    234: { title: 'Christ Is the World’s Light', hasLyricsOrScan: true },
    235: {
      title: 'Christ Is Made the Sure Foundation',
      hasLyricsOrScan: true,
      scriptureReference: 'Ephesians 2:20',
    },
    236: { title: 'I Love Thee', hasLyricsOrScan: true },
    237: { title: 'In the Cross of Christ I Glory', hasLyricsOrScan: true },
    238: {
      title: 'How Sweet the Name!',
      hasLyricsOrScan: true,
      scriptureReference: 'Song of Solomon 1:3',
    },
    239: { title: 'Jesus, Priceless Treasure', hasLyricsOrScan: true },
    240: { title: 'Fairest Lord Jesus', hasLyricsOrScan: true },
    241: { title: 'Jesus, the Very Thought of Thee', hasLyricsOrScan: true },
    242: { title: 'Jesus, Thou Joy of Loving Hearts', hasLyricsOrScan: true },
    243: { title: 'King of Glory, King of Peace', hasLyricsOrScan: true },
    244: { title: 'My Song Shall Be of Jesus' },
    245: { title: 'More About Jesus', hasLyricsOrScan: true },
    246: {
      title: 'Worthy, Worthy Is the Lamb',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 5:12',
    },
    247: { title: 'Come, My Way', hasLyricsOrScan: true },
    248: { title: 'O, How I Love Jesus', hasLyricsOrScan: true },
    249: { title: 'Praise Him! Praise Him!', hasLyricsOrScan: true },
    250: { title: 'O for a Thousand Tongues to Sing', hasLyricsOrScan: true },
    251: { title: 'He Lives' },
    252: {
      title: 'Come, Let Us Sing',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 5:9-13',
    },
    253: {
      title: 'There’s No Other Name Like Jesus',
      hasLyricsOrScan: true,
      scriptureReference: 'Acts 4:12',
    },
    254: { title: 'The Great Physician Now Is Near', hasLyricsOrScan: true },
    255: { title: 'I Cannot Tell Why', hasLyricsOrScan: true },
    256: { title: 'Ye Servants of God', hasLyricsOrScan: true },
    257: { title: 'Come Down, O Love Divine', hasLyricsOrScan: true },
    258: { title: 'Baptize Us Anew', hasLyricsOrScan: true },
    259: { title: 'Draw Us in the Spirit’s Tether', hasLyricsOrScan: true },
    260: { title: 'Hover O’er Me, Holy Spirit', hasLyricsOrScan: true },
    261: { title: 'The Spirit of the Lord Revealed' },
    262: { title: 'Sweet, Sweet Spirit' },
    263: { title: 'Fire of God, Thou Sacred Flame' },
    264: { title: 'O for That Flame of Living Fire', hasLyricsOrScan: true },
    265: { title: 'Breathe on Me, Breath of God', hasLyricsOrScan: true },
    266: { title: 'Spirit of God', hasLyricsOrScan: true },
    267: { title: 'Sprit Divine', hasLyricsOrScan: true },
    268: { title: 'Holy Spirit, Light Divine', hasLyricsOrScan: true },
    269: { title: 'Come, Holy Spirit', hasLyricsOrScan: true },
    270: { title: 'O Holy Dove of God Descending' },
    271: {
      title: 'Break Thou the Bread of Life',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 14:19',
    },
    272: { title: 'Give Me the Bible', hasLyricsOrScan: true },
    273: {
      title: 'Lord, I Have Made Thy Word My Choice',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 119:111',
    },
    274: { title: 'O Word of God Incarnate', hasLyricsOrScan: true },
    275: { title: 'O God of Light', hasLyricsOrScan: true },
    276: { title: 'Thanks to God', hasLyricsOrScan: true },
    277: { title: 'For Your Holy Book We Thank You' },
    278: { title: 'Lord Jesus, Once You Spoke to Men' },
    279: { title: 'Only Trust Him', hasLyricsOrScan: true },
    280: { title: 'Come, Ye Sinners', hasLyricsOrScan: true },
    281: { title: 'I Gave My Life for Thee', hasLyricsOrScan: true },
    282: { title: 'I Hear Thy Welcome Voice', hasLyricsOrScan: true },
    283: { title: 'O Jesus, Thou Art Standing', hasLyricsOrScan: true },
    284: { title: 'For You I Am Praying', hasLyricsOrScan: true },
    285: { title: 'Jesus Calls Us', hasLyricsOrScan: true },
    286: { title: 'Wonderful Words of Life', hasLyricsOrScan: true },
    287: { title: 'Softly and Tenderly', hasLyricsOrScan: true },
    288: { title: 'I Am Going to Calvary', hasScan: true },
    289: { title: 'The Savior Is Waiting' },
    290: { title: 'Turn Your Eyes Upon Jesus', hasLyricsOrScan: true },
    291: { title: 'We Have Not Known Thee', hasLyricsOrScan: true },
    292: { title: 'Jesus, I Come', hasLyricsOrScan: true },
    293: { title: 'Heavenly Father, Bless Us Now', hasLyricsOrScan: true },
    294: { title: 'Power in the Blood', hasLyricsOrScan: true },
    295: { title: 'Chief of Sinners', hasLyricsOrScan: true },
    296: { title: 'Lord, I’m Coming Home', hasLyricsOrScan: true },
    297: {
      title: 'God Be Merciful to Me',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 51',
    },
    298: { title: 'I Lay My Sins on Jesus', hasLyricsOrScan: true },
    299: { title: 'Forgive Our Sins as We Forgive', scriptureReference: 'Matthew 6:12' },
    300: { title: 'Rock of Ages', hasLyricsOrScan: true },
    301: { title: 'Nearer, Still Nearer', hasLyricsOrScan: true },
    302: { title: 'Deeper Yet', hasLyricsOrScan: true },
    303: {
      title: 'Beneath the Cross of Jesus',
      hasLyricsOrScan: true,
      scriptureReference: 'Proverbs 14:26',
    },
    304: { title: 'Faith of Our Fathers', hasLyricsOrScan: true },
    305: { title: 'Give Me Jesus', hasLyricsOrScan: true },
    306: { title: 'Draw Me Nearer', hasLyricsOrScan: true },
    307: { title: 'I Am Coming to the Cross', hasLyricsOrScan: true },
    308: { title: 'Wholly Thine', hasLyricsOrScan: true },
    309: { title: 'I Surrender All', hasLyricsOrScan: true },
    310: { title: 'I Would Draw Nearer to Jesus', hasLyricsOrScan: true },
    311: { title: 'I Would Be Like Jesus', hasLyricsOrScan: true },
    312: { title: 'Near the Cross', hasLyricsOrScan: true },
    313: { title: 'Just as I Am', hasLyricsOrScan: true },
    314: { title: 'Just as IAm', hasLyricsOrScan: true },
    315: { title: 'O for a Closer Walk!', hasLyricsOrScan: true },
    316: { title: 'Live Out Thy Life Within Me', hasLyricsOrScan: true },
    317: { title: 'Lead Me to Calvary', hasLyricsOrScan: true },
    318: { title: 'Whiter Than Snow', hasLyricsOrScan: true },
    319: { title: 'Lord, I Want to Be a Christian', hasLyricsOrScan: true },
    320: { title: 'Lord of Creation' },
    321: { title: 'My Jesus, I Love Thee', hasLyricsOrScan: true },
    322: { title: 'Nothing Between' },
    323: { title: 'O for a Heart to Praise My God!', hasLyricsOrScan: true },
    324: { title: 'Just as I Am, Thine Own to Be', hasLyricsOrScan: true },
    325: { title: 'Jesus, I My Cross Have Taken', hasLyricsOrScan: true },
    326: { title: 'Open My Eyes That I May See', hasLyricsOrScan: true },
    327: { title: 'I’d Rather Have Jesus', hasLyricsOrScan: true },
    328: { title: 'Must Jesus Bear the Cross Alone', hasLyricsOrScan: true },
    329: { title: 'Take the World, but Give Me Jesus', hasLyricsOrScan: true },
    330: { title: 'Take My Life and Let It Be', hasLyricsOrScan: true },
    331: { title: 'O Jesus, I Have Promised', hasLyricsOrScan: true },
    332: { title: 'The Cleansing Wave', hasLyricsOrScan: true },
    333: {
      title: 'On Jordan’s Banks the Baptist’s Cry',
      hasLyricsOrScan: true,
      scriptureReference: 'Luke 3:2-4',
    },
    334: { title: 'Come, Thou Fount of Every Blessing', hasLyricsOrScan: true },
    335: { title: 'What a Wonderful Savior', hasLyricsOrScan: true },
    336: { title: 'There Is a Fountain', hasLyricsOrScan: true },
    337: {
      title: 'Redeemed!',
      hasLyricsOrScan: true,
      scriptureReference: 'Lamentations 3:58',
    },
    338: {
      title: 'Redeemed!',
      hasLyricsOrScan: true,
      scriptureReference: 'Lamentations 3:58',
    },
    339: {
      title: 'God Is My Strong Salvation',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 27:1-3',
    },
    340: { title: 'Jesus Saves', hasLyricsOrScan: true },
    341: { title: 'To God Be the Glory', hasLyricsOrScan: true },
    342: { title: 'Is This a Day of New Beginnings?', hasLyricsOrScan: true },
    343: { title: 'I Will Sing of My Redeemer', hasLyricsOrScan: true },
    344: { title: 'I Love Your Kingdom, Lord', hasLyricsOrScan: true },
    345: { title: 'Christ Is the World’s True Light' },
    346: { title: 'Lord, Who Dost Give to Thy Church', hasLyricsOrScan: true },
    347: { title: 'Built on the Rock' },
    348: { title: 'The Church Has One Foundation', hasLyricsOrScan: true },
    349: { title: 'God Is Love', scriptureReference: '1 John 4:7-8' },
    350: { title: 'Blest Be the Tie That Binds', hasLyricsOrScan: true },
    351: {
      title: 'Thy Hand, O God Has Guided',
      hasLyricsOrScan: true,
      scriptureReference: 'Ephesians 4:5',
    },
    352: { title: 'This Is My Will' },
    353: { title: 'Father, Help Your People', hasLyricsOrScan: true },
    354: { title: 'Thy Love, O God' },
    355: { title: 'Where Cross the Crowded Ways of Life', hasLyricsOrScan: true },
    356: { title: 'All Who Love and Serve Your City', hasLyricsOrScan: true },
    357: { title: 'Come, Labor On', hasLyricsOrScan: true },
    358: { title: 'Far and Near the Fields Are Teeming', hasLyricsOrScan: true },
    359: { title: 'Hark! the Voice of Jesus Calling', hasLyricsOrScan: true },
    360: {
      title: 'From the Eastern Mountains',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 2:1-2',
    },
    361: { title: 'Hark! ‘Tis the Shepherd’s Voice I Hear', hasLyricsOrScan: true },
    362: { title: 'Lift High the Cross', hasLyricsOrScan: true },
    363: { title: 'Lord, Whose Love in Humble Service' },
    364: { title: 'O Jesus Christ, to You', hasLyricsOrScan: true },
    365: { title: 'O Zion, Haste', hasLyricsOrScan: true },
    366: { title: 'O Where Are the Reapers?', hasLyricsOrScan: true },
    367: { title: 'Rescue the Perishing', hasLyricsOrScan: true },
    368: { title: 'Watchman, Blow the Gospel Trumpet', hasLyricsOrScan: true },
    369: { title: 'Bringing in the Sheaves', hasLyricsOrScan: true },
    370: { title: 'Christ for the World', hasLyricsOrScan: true },
    371: { title: 'Lift Him Up', hasLyricsOrScan: true },
    372: {
      title: 'How Beauteous Are Their Feet',
      hasLyricsOrScan: true,
      scriptureReference: 'Isaiah 52:7-9',
    },
    373: { title: 'Seeking the Lost', hasLyricsOrScan: true },
    374: { title: 'Jesus, With Thy Church Abide', hasLyricsOrScan: true },
    375: { title: 'Work, for the Night Is Coming', hasLyricsOrScan: true },
    376: { title: 'All Things Are Thine', hasLyricsOrScan: true },
    377: { title: 'Go Forth, Go Forth With Christ', hasScan: true },
    378: {
      title: 'Go, Preach My Gospel',
      hasLyricsOrScan: true,
      scriptureReference: 'Mark 16:15-17',
    },
    379: { title: 'We Give This Child to You' },
    380: { title: 'Welcome, Day of Sweet Repose', hasLyricsOrScan: true },
    381: { title: 'Holy Sabbath Day of Rest', hasLyricsOrScan: true },
    382: { title: 'O Day of Rest and Gladness', hasLyricsOrScan: true },
    383: { title: 'O Day of Rest and Gladness', hasLyricsOrScan: true },
    384: { title: 'Safely Through Another Week', hasLyricsOrScan: true },
    385: { title: 'Crowing Jewel of Creation' },
    386: { title: 'The Sacred Anthem' },
    387: { title: 'Come, O Sabbath Day', hasLyricsOrScan: true },
    388: { title: 'Don’t Forget the Sabbath', hasLyricsOrScan: true },
    389: { title: 'Light of Light, Enlighten Me', hasLyricsOrScan: true },
    390: { title: 'We Love Thy Sabbath, Lord', hasLyricsOrScan: true },
    391: { title: 'Welcome, Welcome, Day of Rest', hasLyricsOrScan: true },
    392: { title: 'Dear Lord, We Come at Set of Sun' },
    393: { title: 'Lord of the Sabbath', hasLyricsOrScan: true },
    394: { title: 'Far From All Care', hasLyricsOrScan: true },
    395: { title: 'As Birds Unto the Genial Homeland', hasLyricsOrScan: true },
    396: { title: 'Lord God, Your Love Has Called Us Here', hasLyricsOrScan: true },
    397: { title: 'An Upper Room', hasLyricsOrScan: true },
    398: { title: 'Bread of the World', hasLyricsOrScan: true },
    399: { title: 'Beneath the Forms of Outward Rite', scriptureReference: 'Mark 14:15' },
    400: { title: 'I Come With Joy', hasLyricsOrScan: true },
    401: { title: 'In Imitation, Lord of Thee', hasLyricsOrScan: true },
    402: {
      title: 'By Christ Redeemed',
      hasLyricsOrScan: true,
      scriptureReference: '1 Corinthians 11:23-26',
    },
    403: {
      title: 'Let Us Break Bread Together',
      hasLyricsOrScan: true,
      scriptureReference: 'Malachi 4:2',
    },
    404: { title: 'Now Let Us From This Table Rise', hasLyricsOrScan: true },
    405: { title: 'O God, Unseen, Yet Ever Near', hasLyricsOrScan: true },
    406: { title: 'Love Consecrates the Humblest Act', hasLyricsOrScan: true },
    407: { title: 'Sent Forth by God’s Blessing' },
    408: { title: 'Lord, Enthroned in Heavenly Splendor', hasLyricsOrScan: true },
    409: { title: 'Jesus Invites His Saints', hasLyricsOrScan: true },
    410: { title: 'Thy Broken Body, Gracious Lord', hasLyricsOrScan: true },
    411: { title: 'The Son of God Proclaim' },
    412: { title: 'Cover With His Life', hasLyricsOrScan: true },
    413: {
      title: 'God Has Spoken by His Prophets',
      hasLyricsOrScan: true,
      scriptureReference: 'Hebrews 1:1-2',
    },
    414: {
      title: 'Fruitful Trees, the Spirit’s Sowing',
      hasLyricsOrScan: true,
      scriptureReference: 'Galatians 5:22-23',
    },
    415: {
      title: 'Christ the Lord, All Power Possessing',
      scriptureReference: 'Matthew 28:18-20',
    },
    416: { title: 'The Judgment Has Set', hasLyricsOrScan: true },
    417: { title: 'O Solemn Thought', hasLyricsOrScan: true },
    418: { title: 'Day of Judgment, Day of Wonders!', hasLyricsOrScan: true },
    419: { title: 'Soon Shall the Trump of God', hasLyricsOrScan: true },
    420: { title: 'Jerusalem, My Happy Home', hasLyricsOrScan: true },
    421: { title: 'For All the Saints', hasLyricsOrScan: true },
    422: { title: 'Marching to Zion', hasLyricsOrScan: true },
    423: { title: 'Glorious Things of Thee Are Spoken', hasLyricsOrScan: true },
    424: { title: 'For Thee, O Dear, Dear Country', hasLyricsOrScan: true },
    425: { title: 'Holy, Holy, Is What the Angels Sing', hasLyricsOrScan: true },
    426: { title: 'I Shall See the King', hasLyricsOrScan: true },
    427: { title: 'No Night There', hasLyricsOrScan: true },
    428: { title: 'Sweet By and By', hasLyricsOrScan: true },
    429: { title: 'Jerusalem the Golden', hasLyricsOrScan: true },
    430: { title: 'Joy By and By', hasLyricsOrScan: true },
    431: { title: 'Over Yonder', hasLyricsOrScan: true },
    432: { title: 'Shall We Gather at the River', hasLyricsOrScan: true },
    433: { title: 'Ten Thousand Times Ten Thousand', hasLyricsOrScan: true },
    434: { title: 'We Speak of the Realms', hasLyricsOrScan: true },
    435: { title: 'The Glory Song', hasLyricsOrScan: true },
    436: {
      title: 'The Homeland',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 21:4',
    },
    437: {
      title: 'I’m Going Home',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 21:4',
    },
    438: { title: 'You Will See Your Lord A-Coming', hasLyricsOrScan: true },
    439: { title: 'How Far From Home?', hasLyricsOrScan: true },
    440: { title: 'How Cheering Is the Christian’s Hope', hasLyricsOrScan: true },
    441: {
      title: 'I Saw One Weary',
      hasLyricsOrScan: true,
      scriptureReference: 'Titus 2:13',
    },
    442: { title: 'How Sweet Are the Tidings', hasLyricsOrScan: true },
    443: {
      title: 'There’ll Be No Sorrow There',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 21:4',
    },
    444: { title: 'I’m a Pilgrim', hasLyricsOrScan: true },
    445: { title: 'I’m But a Stranger Here', hasLyricsOrScan: true },
    446: {
      title: 'Lo, What a Glorious Sight Appears',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 21:1-4',
    },
    447: {
      title: 'Long Upon the Mountains',
      hasLyricsOrScan: true,
      scriptureReference: 'Ezekiel 34:12',
    },
    448: { title: 'O, When Shall I See Jesus', hasLyricsOrScan: true },
    449: { title: 'Never Part Again', hasLyricsOrScan: true },
    450: { title: 'Beautiful Zion', hasLyricsOrScan: true },
    451: { title: 'Together Let Us Sweetly Live', hasLyricsOrScan: true },
    452: { title: 'What Heavenly Music', hasLyricsOrScan: true },
    453: { title: 'We Have Heard', hasLyricsOrScan: true },
    454: { title: 'Don’t You See My Jesus Coming?', hasLyricsOrScan: true },
    455: { title: 'Immortal Love, Forever Full', hasLyricsOrScan: true },
    456: { title: 'My Lord and I', hasLyricsOrScan: true },
    457: { title: 'I Love to Tell the Story', hasLyricsOrScan: true },
    458: { title: 'More Love to Thee', hasLyricsOrScan: true },
    459: { title: 'As the Bridegroom to His Chosen', hasLyricsOrScan: true },
    460: { title: 'As Water to the Thirsty', hasLyricsOrScan: true },
    461: {
      title: 'Be Still, My Soul',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 46:10',
    },
    462: { title: 'Blessed Assurance, Jesus Is Mine!', hasLyricsOrScan: true },
    463: {
      title: 'Peace, Perfect Peace',
      hasLyricsOrScan: true,
      scriptureReference: 'Isaiah 26:3',
    },
    464: { title: 'When I Can Read My Title Clear', hasLyricsOrScan: true },
    465: { title: 'I Heard the Voice of Jesus', hasLyricsOrScan: true },
    466: { title: 'Wonderful Peace', hasLyricsOrScan: true },
    467: { title: 'Life Is Great! So Sing About It', hasLyricsOrScan: true },
    468: { title: 'A Child of the King', hasLyricsOrScan: true },
    469: {
      title: 'Leaning on the Everlasting Arms',
      hasLyricsOrScan: true,
      scriptureReference: 'Deuteronomy 33:27',
    },
    470: { title: 'There’s Sunshine in My Soul Today', hasLyricsOrScan: true },
    471: { title: 'Grant Us Your Peace', hasLyricsOrScan: true },
    472: { title: 'A Song of Heaven and Homeland', hasLyricsOrScan: true },
    473: {
      title: 'Nearer My God, to Thee',
      hasLyricsOrScan: true,
      scriptureReference: 'Genesis 28:10-19',
    },
    474: { title: 'Take the Name of Jesus With You', hasLyricsOrScan: true },
    475: { title: 'Balm in Gilead', hasLyricsOrScan: true },
    476: { title: 'Burdens Are Lifted at Calvary' },
    477: { title: 'Come, Ye Disconsolate', hasLyricsOrScan: true },
    478: { title: 'Sweet Hour of Prayer', hasLyricsOrScan: true },
    479: { title: 'Tread Softly', hasLyricsOrScan: true },
    480: { title: 'Dear Lord and Father', hasLyricsOrScan: true },
    481: { title: 'Dear Lord and Father', hasLyricsOrScan: true },
    482: { title: 'Father, Lead Me Day by Day', hasLyricsOrScan: true },
    483: { title: 'I Need Thee Every Hour', hasLyricsOrScan: true },
    484: { title: 'I Need Thee, Precious Jesus', hasLyricsOrScan: true },
    485: { title: 'I Must Tell Jesus', hasLyricsOrScan: true },
    486: { title: 'I Do Believe', hasLyricsOrScan: true },
    487: {
      title: 'In the Garden',
      hasLyricsOrScan: true,
      scriptureReference: 'John 20:15-17',
    },
    488: { title: 'At First I Prayed for Light', hasLyricsOrScan: true },
    489: { title: 'Jesus, Lover of My Soul', hasLyricsOrScan: true },
    490: { title: 'Jesus, Lover of My Soul', hasLyricsOrScan: true },
    491: { title: 'In the Hour of Trial', hasLyricsOrScan: true },
    492: { title: 'Like Jesus', hasLyricsOrScan: true },
    493: { title: 'Fill My Cup, Lord' },
    494: {
      title: 'We Would See Jesus',
      hasLyricsOrScan: true,
      scriptureReference: 'John 12:21',
    },
    495: { title: 'Near the Heart of God', hasLyricsOrScan: true },
    496: {
      title: 'Eternal Love, We Have No Good',
      hasLyricsOrScan: true,
      scriptureReference: 'Revelation 8:3',
    },
    497: { title: 'O Gracious Father of Mankind', hasLyricsOrScan: true },
    498: { title: 'Still, Still With Thee', hasLyricsOrScan: true },
    499: { title: 'What a Friend We Have in Jesus', hasLyricsOrScan: true },
    500: {
      title: 'Take Time to Be Holy',
      hasLyricsOrScan: true,
      scriptureReference: '1 Peter 1:16',
    },
    501: { title: 'Tis the Blessed Hour of Prayer', hasLyricsOrScan: true },
    502: { title: 'Sun of My Soul', hasLyricsOrScan: true },
    503: { title: 'A Quiet Place' },
    504: { title: 'Lord Jesus, Think on Me', hasLyricsOrScan: true },
    505: { title: 'I Need the Prayers', hasLyricsOrScan: true },
    506: {
      title: 'A Mighty Fortress',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 46:1',
    },
    507: { title: 'Moment by Moment', hasLyricsOrScan: true },
    508: { title: 'Anywhere With Jesus', hasLyricsOrScan: true },
    509: { title: 'How Firm a Foundation', hasLyricsOrScan: true },
    510: {
      title: 'If You But Trust in God to Guide You',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 55:22',
    },
    511: {
      title: 'I Know Whom I Have Believed',
      hasLyricsOrScan: true,
      scriptureReference: '2 Timothy 1:12',
    },
    512: { title: 'Just When I Need Him Most', hasLyricsOrScan: true },
    513: {
      title: 'In Heavenly Love Abiding',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 23',
    },
    514: { title: 'Lord of Our Life', hasLyricsOrScan: true },
    515: { title: 'The Lord is My Light', hasLyricsOrScan: true },
    516: { title: 'All the Way', hasLyricsOrScan: true },
    517: { title: 'My Faith Looks Up to Thee', hasLyricsOrScan: true },
    518: {
      title: 'Standing on the Promises',
      hasLyricsOrScan: true,
      scriptureReference: '2 Peter 1:4',
    },
    519: {
      title: 'Give to the Winds Your Fears',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 37:5',
    },
    520: { title: 'He Hideth My Soul', hasLyricsOrScan: true },
    521: {
      title: 'Depth of Mercy',
      hasLyricsOrScan: true,
      scriptureReference: '1 Timothy 1:15',
    },
    522: { title: 'My Hope Is Built on Nothing Less', hasLyricsOrScan: true },
    523: { title: 'My Faith Has Found a Resting Place', hasLyricsOrScan: true },
    524: { title: 'Tis So Sweet to Trust in Jesus', hasLyricsOrScan: true },
    525: {
      title: 'Hiding in Thee',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 61:1-2',
    },
    526: { title: 'Because He Lives' },
    527: {
      title: 'From Every Stormy Wind',
      hasLyricsOrScan: true,
      scriptureReference: 'Exodus 25:22',
    },
    528: { title: 'A Shelter in the Time of Storm', hasLyricsOrScan: true },
    529: { title: 'Under His Wings', hasLyricsOrScan: true },
    530: { title: 'Is Is Well With My Soul', hasLyricsOrScan: true },
    531: {
      title: 'We’ll Build on the Rock',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 7:24-26',
    },
    532: {
      title: 'Day by Day',
      hasLyricsOrScan: true,
      scriptureReference: 'Deuteronomy 33:25',
    },
    533: { title: 'O for a Faith', hasLyricsOrScan: true },
    534: { title: 'Will Your Anchor Hold?', hasLyricsOrScan: true },
    535: {
      title: 'I Am Trusting Thee, Lord Jesus',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 71:1',
    },
    536: { title: 'God, Who Stretched the Spangled Heavens', hasLyricsOrScan: true },
    537: {
      title: 'He Leadeth Me',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 23:2',
    },
    538: { title: 'Guide Me, O Thou Great Jehovah', hasLyricsOrScan: true },
    539: { title: 'I Will Early Seek the Savior', hasLyricsOrScan: true },
    540: { title: 'Gentle Jesus, Meek and Mild', hasLyricsOrScan: true },
    541: {
      title: 'Lord, Speak to Me',
      hasLyricsOrScan: true,
      scriptureReference: 'Romans 14:7',
    },
    542: { title: 'Jesus, Friend So Kind', hasLyricsOrScan: true },
    543: { title: 'Jesus, Friend of Little Children', hasLyricsOrScan: true },
    544: { title: 'Jesus, Son of Blessed Mary', hasLyricsOrScan: true },
    545: { title: 'Savior, Like a Shepherd', hasLyricsOrScan: true },
    546: {
      title: 'The Lord’s My Shepherd',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 23',
    },
    547: { title: 'Be Thou My Vision' },
    548: { title: 'Now Praise the Hidden God of Love', hasLyricsOrScan: true },
    549: {
      title: 'Loving Shepherd of Thy Sheep',
      hasLyricsOrScan: true,
      scriptureReference: 'John 10:27-28',
    },
    550: { title: 'Every Flower That Grows', hasLyricsOrScan: true },
    551: { title: 'Jesus, Savior, Pilot Me', hasLyricsOrScan: true },
    552: {
      title: 'The Lord’s My Shepherd',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 23',
    },
    553: { title: 'Jesus, Guide Our Way', hasLyricsOrScan: true },
    554: { title: 'O Let Me Walk With Thee', hasLyricsOrScan: true },
    555: {
      title: 'Shepherd of Tender Youth',
      hasLyricsOrScan: true,
      scriptureReference: 'Deuteronomy 32:7',
    },
    556: { title: 'As Saints of Old', hasLyricsOrScan: true },
    557: { title: 'Come, Ye Thankful People', hasLyricsOrScan: true },
    558: { title: 'For the Fruits of His Creation', hasLyricsOrScan: true },
    559: { title: 'Now Thanks We All Our God', hasLyricsOrScan: true },
    560: {
      title: 'Let All Things Now Living',
      hasLyricsOrScan: true,
      scriptureReference: '1 Chronicles 16:32',
    },
    561: { title: 'We Plow the Fields', hasLyricsOrScan: true },
    562: { title: 'Come, Sing a Song of Harvest', hasLyricsOrScan: true },
    563: { title: 'Praise and Thanksgiving' },
    564: { title: 'For Sunrise Hope and Sunset Calm', hasLyricsOrScan: true },
    565: { title: 'For the Beauty of the Earth', hasLyricsOrScan: true },
    566: { title: 'Father, We Thank You' },
    567: { title: 'Have Thine Own Way, Lord', hasLyricsOrScan: true },
    568: { title: 'Make Me a Captive, Lord', hasLyricsOrScan: true },
    569: { title: 'Pass Me Not, O Gentle Savior', hasLyricsOrScan: true },
    570: { title: 'Not I, but Christ', hasLyricsOrScan: true },
    571: { title: 'What Does the Lord Require?', scriptureReference: 'Micah 6:8' },
    572: { title: 'Give of Your Best to the Master', hasLyricsOrScan: true },
    573: { title: 'I’ll Go Where You Want Me to Go', hasLyricsOrScan: true },
    574: { title: 'O Master, Let Me Walk With Thee', hasLyricsOrScan: true },
    575: { title: 'Let Your Heart Be Broken' },
    576: { title: 'Awake, Awake to Love and Work', hasLyricsOrScan: true },
    577: { title: 'In the Heart of Jesus', hasLyricsOrScan: true },
    578: { title: 'Se Send I You', scriptureReference: 'John 20:21' },
    579: { title: 'Tis Love That Makes Us Happy', hasLyricsOrScan: true },
    580: { title: 'This Little Light of Mine', hasLyricsOrScan: true },
    581: { title: 'When the Church of Jesus', hasLyricsOrScan: true },
    582: { title: 'Working, O Christ, With Thee', hasLyricsOrScan: true },
    583: {
      title: 'You That Know the Lord',
      hasLyricsOrScan: true,
      scriptureReference: '1 Peter 2:4-10',
    },
    584: { title: 'There’s a Spirit in the Air', hasLyricsOrScan: true },
    585: { title: 'When Christ Was Lifted From the Earth', hasLyricsOrScan: true },
    586: { title: 'What Joy It Is to Worship Here', hasLyricsOrScan: true },
    587: { title: 'In Christ There Is No East nor West', hasLyricsOrScan: true },
    588: { title: 'Lord of All Nations', scriptureReference: 'Acts 10:34-35' },
    589: {
      title: 'Holy Spirit, Gracious Guest',
      hasLyricsOrScan: true,
      scriptureReference: '1 Corinthians 13',
    },
    590: { title: 'Trust and Obey', hasLyricsOrScan: true },
    591: { title: 'In Our Work and In Our Play', hasLyricsOrScan: true },
    592: {
      title: 'Watchman, Tell Us of the Night',
      hasLyricsOrScan: true,
      scriptureReference: 'Isaiah 21:11-12',
    },
    593: { title: 'In Times Like These' },
    594: { title: 'Heir of the Kingdom', hasLyricsOrScan: true },
    595: { title: 'Let Every Lamp', hasLyricsOrScan: true },
    596: {
      title: 'Look for the Waymarks',
      hasLyricsOrScan: true,
      scriptureReference: 'Daniel 2:31-44',
    },
    597: { title: 'Ye Servants of the Lord', hasLyricsOrScan: true },
    598: { title: 'Watch, Ye Saints', hasLyricsOrScan: true },
    599: {
      title: 'Rejoice, Rejoice, Believers',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 25:1-7',
    },
    600: { title: 'Hold Fast Till I Come', hasLyricsOrScan: true },
    601: { title: 'Watchmen, on the Walls of Zion', hasLyricsOrScan: true },
    602: { title: 'O Brother, Be Faithful', hasLyricsOrScan: true },
    603: {
      title: 'Christian, Seek Not Repose',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 26:41',
    },
    604: {
      title: 'We Know Not the Hour',
      hasLyricsOrScan: true,
      scriptureReference: 'Matthew 24:36-42',
    },
    605: { title: 'My Soul, Be on Thy Guard', hasLyricsOrScan: true },
    606: { title: 'Once to Every Man and Nation', hasLyricsOrScan: true },
    607: { title: 'God of Grace and God of Glory', hasLyricsOrScan: true },
    608: { title: 'Faith Is the Victory', hasLyricsOrScan: true },
    609: { title: 'Am I a Soldier of the Cross?', hasLyricsOrScan: true },
    610: { title: 'Stand Like the Brave', hasLyricsOrScan: true },
    611: {
      title: 'Awake, My Soul!',
      hasLyricsOrScan: true,
      scriptureReference: 'Philippians 3:14',
    },
    612: { title: 'Onward, Christian Soldiers!', hasLyricsOrScan: true },
    613: {
      title: 'Fight the Good Fight',
      hasLyricsOrScan: true,
      scriptureReference: '1 Timothy 6:12',
    },
    614: { title: 'Sound the Battle Cry', hasLyricsOrScan: true },
    615: { title: 'Rise Up, O Church of God' },
    616: {
      title: 'Soldiers of Christ, Arise',
      hasLyricsOrScan: true,
      scriptureReference: 'Ephesians 6:13',
    },
    617: { title: 'We Are Living, We Are Dwelling', hasLyricsOrScan: true },
    618: {
      title: 'Stand Up! Stand Up for Jesus!',
      hasLyricsOrScan: true,
      scriptureReference: 'Ephesians 6:14',
    },
    619: { title: 'Lead On, O King Eternal', hasLyricsOrScan: true },
    620: { title: 'On Jordan’s Stormy Banks' },
    621: { title: 'Gracious Father, Guard Thy Children', hasLyricsOrScan: true },
    622: { title: 'Come, Come, Ye Saints', hasLyricsOrScan: true },
    623: { title: 'I Will Follow Thee', hasLyricsOrScan: true },
    624: { title: 'I Want Jesus to Walk With Me', hasLyricsOrScan: true },
    625: { title: 'Higher Ground', hasLyricsOrScan: true },
    626: { title: 'In a Little While We’re Going Home', hasLyricsOrScan: true },
    627: { title: 'Jacob’s Ladder', hasLyricsOrScan: true },
    628: {
      title: 'As Jacob With Travel Was Weary',
      hasLyricsOrScan: true,
      scriptureReference: 'Genesis 28:12',
    },
    629: {
      title: 'O Happy Band of Pilgrims',
      hasLyricsOrScan: true,
      scriptureReference: '1 Peter 1:6-7',
    },
    630: { title: 'Rise, My Soul, and Stretch Thy Wings', hasLyricsOrScan: true },
    631: { title: 'When on Life a Darkness Falls', hasLyricsOrScan: true },
    632: { title: 'Until Then' },
    633: { title: 'When We All Get to Heaven', hasLyricsOrScan: true },
    634: { title: 'Come, All Christians, Be Committed', hasLyricsOrScan: true },
    635: { title: 'Lord of All Good' },
    636: { title: 'God, Whose Giving Knows No Ending', hasLyricsOrScan: true },
    637: { title: 'Son of God, Eternal Savior', hasLyricsOrScan: true },
    638: { title: 'The Wise May Bring Their Learning', hasLyricsOrScan: true },
    639: { title: 'A Diligent and Grateful Heart' },
    640: { title: 'For Beauty of Meadows' },
    641: { title: 'God in His Love for Us', hasLyricsOrScan: true },
    642: { title: 'We Praise Thee With Our Minds' },
    643: { title: 'Father, Who on Us Do Shower', hasLyricsOrScan: true },
    644: { title: 'O God, Whose Will Is Life and Good', hasLyricsOrScan: true },
    645: { title: 'God of Our Fathers', hasLyricsOrScan: true },
    646: { title: 'To the Name That Brings Salvation', hasLyricsOrScan: true },
    647: { title: 'Mine Eyes Have Seen the Glory', hasLyricsOrScan: true },
    648: { title: 'I Vow to Thee, My Country', hasLyricsOrScan: true },
    649: { title: 'Lord, While for All Mankind', hasLyricsOrScan: true },
    650: { title: 'Our Father, by Whose Name' },
    651: { title: 'Happy the Home That Welcomes You' },
    652: { title: 'Love at Home', hasLyricsOrScan: true },
    653: { title: 'Lead Them, My God, to Thee', hasLyricsOrScan: true },
    654: { title: 'Lord, Bless Our Homes' },
    655: { title: 'Happy the Home', hasLyricsOrScan: true },
    656: { title: 'O Perfect Love', hasLyricsOrScan: true },
    657: { title: 'O God, From Whom Mankind', hasLyricsOrScan: true },
    658: { title: 'Heavenly Father, Hear Our Prayer' },
    659: { title: 'May the Grace of Christ Our Savior', hasLyricsOrScan: true },
    660: { title: 'Glory Be to the Father', hasLyricsOrScan: true },
    661: { title: 'Holy, Holy, Holy', hasLyricsOrScan: true },
    662: { title: 'Let All Mortals Flesh Keep Silence', hasLyricsOrScan: true },
    663: { title: 'Amens', hasLyricsOrScan: true },
    664: { title: 'Sevenfold Amen', hasLyricsOrScan: true },
    665: { title: 'All Things Come of Thee', hasLyricsOrScan: true },
    666: {
      title: 'Cast Thy Burden Upon the Lord',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 55:22',
    },
    667: { title: 'Lord, Bless Thy Word to Every Heart', hasLyricsOrScan: true },
    668: { title: 'O Thou Who Hearest', hasLyricsOrScan: true },
    669: {
      title: 'The Lord Bless You and Keep You',
      hasLyricsOrScan: true,
      scriptureReference: 'Numbers 6:24-26',
    },
    670: { title: 'We Give Thee But Thine Own', hasLyricsOrScan: true },
    671: { title: 'As We Come to You in Prayer' },
    672: { title: 'Spirit of the Living God' },
    673: { title: 'May God Be With You' },
    674: { title: 'Shalom' },
    675: { title: 'May the Lord Bless and Keep You', hasLyricsOrScan: true },
    676: { title: 'Thy Word Is a Lantern', hasLyricsOrScan: true },
    677: { title: 'Heavenly Father, to Thee We Pray' },
    678: { title: 'God Be in My Head', hasLyricsOrScan: true },
    679: { title: 'God Be in My Head', hasLyricsOrScan: true },
    680: { title: 'Holy Spirit, Hear Us', hasLyricsOrScan: true },
    681: { title: 'This Is the Day the Lord Hath Made', hasLyricsOrScan: true },
    682: { title: 'As You Have Promised, Lord', scriptureReference: 'Luke 2:29-32' },
    683: {
      title: 'Jesus Stand Among Us',
      hasLyricsOrScan: true,
      scriptureReference: 'John 20:19',
    },
    684: { title: 'Hear Our Prayer, O Lord', hasLyricsOrScan: true },
    685: { title: 'Cause Me to Hear' },
    686: { title: 'Bless Thou the Gifts', hasLyricsOrScan: true },
    687: { title: 'The Lord Is in His Holy Temple', hasLyricsOrScan: true },
    688: { title: 'Surely, Surely' },
    689: { title: 'Day by Day, Dear Lord', hasLyricsOrScan: true },
    690: { title: 'Dismiss Us, Lord, With Blessing', hasLyricsOrScan: true },
    691: {
      title: 'Lead Me, Lord',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 5:8',
    },
    692: { title: 'The Lord Is in His Holy Temple', hasLyricsOrScan: true },
    693: {
      title: 'Almighty Father',
      hasLyricsOrScan: true,
      scriptureReference: 'Isaiah 30:18',
    },
    694: {
      title: 'Praise God, From Whom All Blessings',
      hasLyricsOrScan: true,
      scriptureReference: 'Psalm 148:1-2',
    },
  },
};
