import { MaterialCommunityIcons } from '@expo/vector-icons';

export interface SearchableItem {
  title: string;
  keywords: string[];
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  route: string;
}

export const ALL_SEARCH_LABELS: Record<string, any> = {
  en: {
    searchPlaceholder: 'Search app...',
    home: {
      title: 'Home',
      keywords: ['welcome', 'start', 'pulse', 'livestream', 'happening'],
    },
    community: {
      title: 'Community',
      keywords: [
        'events',
        'schedule',
        'sabbath',
        'groups',
        'calendar',
        'volunteer',
        'in-person',
        'hub',
        'service',
        'fellowship',
        'small groups',
        'gathering',
        'roles',
      ],
    },
    resources: {
      title: 'Resources',
      keywords: [
        'video',
        'preach',
        'message',
        'bible',
        'hymnal',
        'spiritual',
        'scripture',
        'worship',
        'sermons',
        'watch',
        'listen',
        'library',
        'pdf',
        'devotional',
        'youtube',
        'spotify',
        'podcast',
        'archive',
        'reader',
      ],
    },
    bible: {
      title: 'Holy Bible',
      keywords: ['scripture', 'word', 'verse', 'read', 'chapter', 'testament'],
    },
    hymnal: {
      title: 'English Hymnal',
      keywords: ['songs', 'lyrics', 'music', 'sing', 'worship', 'praise'],
    },
    aboutSDA: {
      title: 'About Denomination',
      keywords: ['sda', 'adventist', 'beliefs', 'doctrine', '28'],
    },
    aboutHistory: {
      title: 'Our History',
      keywords: ['history', 'church', 'origins', 'milestones'],
    },
    connect: {
      title: 'Connect',
      keywords: [
        'contact',
        'email',
        'phone',
        'location',
        'call',
        'map',
        'directions',
        'address',
        'staff',
      ],
    },
    give: {
      title: 'Tithe & Offering',
      keywords: ['give', 'tithe', 'offering', 'donation', 'tithing'],
    },
    team: { title: 'Meet Our Team', keywords: ['staff', 'pastors', 'elders', 'team'] },
    bulletin: {
      title: 'Weekly Bulletin',
      keywords: ['program', 'announcements', 'news'],
    },
    events: {
      title: 'Upcoming Events',
      keywords: ['announcements', 'news', 'calendar', 'special', 'programs', 'events'],
    },
    baptism: { title: 'Joining the Church', keywords: ['baptism', 'membership', 'join'] },
    worship: { title: 'Sabbath Worship', keywords: ['service', 'program', 'saturday'] },
    fellowship: { title: 'Fellowship', keywords: ['groups', 'lunch', 'gathering'] },
    roster: {
      title: 'Service Roster',
      keywords: ['volunteer', 'assignments', 'schedule'],
    },
    prayer: { title: 'Prayer Wall', keywords: ['requests', 'intercession', 'community'] },
    language: {
      title: 'Language',
      keywords: ['chinese', 'spanish', 'english', 'translate', 'settings'],
    },
    darkMode: {
      title: 'Dark Mode',
      keywords: ['theme', 'appearance', 'night', 'settings', 'dark'],
    },
  },
  zh: {
    searchPlaceholder: '搜尋...',
    home: {
      title: '首頁',
      keywords: ['歡迎', '開始', 'home', '脈搏', '直播'],
    },
    community: {
      title: '教會社群',
      keywords: [
        '活動',
        '時間表',
        '安息日',
        '小組',
        '義工',
        'calendar',
        'community',
        '中心',
        '服事',
        '團契',
        '聚會',
        '小組',
      ],
    },
    resources: {
      title: '資源庫',
      keywords: [
        '視頻',
        '證道',
        '信息',
        '聖經',
        '詩歌',
        'sermons',
        'resources',
        '圖書館',
        '靈修',
        '敬拜',
        '收看',
        '收聽',
        'youtube',
        'spotify',
        'podcast',
        '檔案',
      ],
    },
    bible: {
      title: '聖經',
      keywords: ['經文', '閱讀', '聖言', 'scripture', 'bible'],
    },
    hymnal: {
      title: '英文詩歌本',
      keywords: ['讚美詩', '歌詞', '音樂', '敬拜', 'hymnal', 'music'],
    },
    aboutSDA: {
      title: '關於教派',
      keywords: ['復臨安息日會', '信仰', '教義', '28條', 'sda'],
    },
    aboutHistory: {
      title: '我們的歷史',
      keywords: ['歷史', '教會', '起源', '發展'],
    },
    connect: {
      title: '聯繫我們',
      keywords: [
        '聯絡',
        '電子郵件',
        '電話',
        '地點',
        '電郵',
        '地圖',
        '導航',
        '地址',
        '路線',
        'connect',
        'contact',
        'email',
        'call',
        'map',
        '同工',
      ],
    },
    give: {
      title: '奉獻',
      keywords: ['什一', '奉獻', '捐款', 'give', 'tithe', 'tithing'],
    },
    team: { title: '認識我們的團隊', keywords: ['同工', '牧師', '長老', 'team'] },
    bulletin: { title: '每週週報', keywords: ['程序', '報告', 'bulletin'] },
    events: {
      title: '近期活動',
      keywords: ['報告', '公告', '消息', '日曆', '特別項目', 'events'],
    },
    baptism: { title: '加入教會', keywords: ['浸禮', '會籍', 'baptism'] },
    worship: { title: '安息日崇拜', keywords: ['崇拜', '聚會', 'worship'] },
    fellowship: { title: '團契', keywords: ['小組', '午餐', 'fellowship'] },
    roster: { title: '服事安排', keywords: ['義工', '服事表', 'roster'] },
    prayer: { title: '教會禱告牆', keywords: ['代禱', '請求', 'prayer'] },
    language: {
      title: '語言設定',
      keywords: ['中文', '英文', '西班牙文', '翻譯', 'language', '設定'],
    },
    darkMode: {
      title: '深色模式',
      keywords: ['theme', 'dark mode', '主題', '外觀', 'settings', '深色'],
    },
  },
  'zh-cn': {
    searchPlaceholder: '搜索...',
    home: {
      title: '首页',
      keywords: ['欢迎', '开始', 'home', '脉搏', '直播'],
    },
    community: {
      title: '教会社区',
      keywords: [
        '活动',
        '时间表',
        '安息日',
        '日历',
        '小组',
        '义工',
        'calendar',
        'community',
        '中心',
        '服事',
        '团契',
        '聚会',
      ],
    },
    resources: {
      title: '资源库',
      keywords: [
        '视频',
        '证道',
        '信息',
        '圣经',
        '诗歌',
        'sermons',
        'resources',
        '图书馆',
        '灵修',
        '敬拜',
        '收看',
        '收听',
        'youtube',
        'spotify',
        'podcast',
        '存档',
      ],
    },
    bible: {
      title: '圣经',
      keywords: ['经文', '阅读', '圣言', 'scripture', 'bible'],
    },
    hymnal: {
      title: '英文诗歌本',
      keywords: ['赞美诗', '歌词', '音乐', '敬拜', 'hymnal', 'music'],
    },
    aboutSDA: {
      title: '关于教派',
      keywords: ['复临安息日会', '信仰', '教义', '28条', 'sda'],
    },
    aboutHistory: {
      title: '我们的历史',
      keywords: ['历史', '教会', '起源', '发展'],
    },
    connect: {
      title: '联系我们',
      keywords: [
        '联络',
        '电子邮件',
        '电话',
        '电邮',
        '地点',
        '地图',
        '导航',
        '地址',
        '路线',
        'connect',
        'contact',
        'email',
        'phone',
        'call',
        'map',
        '同工',
      ],
    },
    give: {
      title: '奉献',
      keywords: ['什一', '奉献', '捐款', 'give', 'tithe'],
    },
    team: { title: '认识我们的团队', keywords: ['同工', '牧师', '长老', 'team'] },
    bulletin: { title: '每周周报', keywords: ['程序', '报告', 'bulletin'] },
    events: {
      title: '近期活动',
      keywords: ['报告', '公告', '消息', '日历', '特别项目', 'events'],
    },
    baptism: { title: '加入教会', keywords: ['浸礼', '会籍', 'baptism'] },
    worship: { title: '安息日崇拜', keywords: ['崇拜', '聚会', 'worship'] },
    fellowship: { title: '团契', keywords: ['小组', '午餐', 'fellowship'] },
    roster: { title: '服事安排', keywords: ['义工', '服事表', 'roster'] },
    prayer: { title: '教会祷告墙', keywords: ['代祷', '请求', 'prayer'] },
    language: {
      title: '语言设置',
      keywords: ['中文', '英文', '西班牙文', '翻译', 'language', '设置'],
    },
    darkMode: {
      title: '深色模式',
      keywords: ['theme', 'dark mode', '主题', '外观', 'settings', '深色'],
    },
  },
  es: {
    searchPlaceholder: 'Buscar...',
    home: {
      title: 'Inicio',
      keywords: ['bienvenido', 'comenzar', 'home', 'pulso', 'en vivo'],
    },
    community: {
      title: 'Comunidad',
      keywords: [
        'eventos',
        'horario',
        'sábado',
        'grupos',
        'voluntario',
        'calendar',
        'community',
        'centro',
        'servicio',
        'compañerismo',
        'grupos',
        'reunión',
        'horario',
        'calendario',
      ],
    },
    resources: {
      title: 'Recursos',
      keywords: [
        'video',
        'predicación',
        'mensaje',
        'biblia',
        'escritura',
        'adoración',
        'sermones',
        'ver',
        'escuchar',
        'himnario',
        'sermons',
        'resources',
        'biblioteca',
        'devocional',
        'youtube',
        'spotify',
        'podcast',
        'archivo',
      ],
    },
    bible: {
      title: 'Santa Biblia',
      keywords: ['escritura', 'palabra', 'versículo', 'leer', 'testamento'],
    },
    hymnal: {
      title: 'Himnario en Inglés',
      keywords: ['cantos', 'letras', 'música', 'cantar', 'adoración'],
    },
    aboutSDA: {
      title: 'Sobre la Denominación',
      keywords: ['adventista', 'creencias', 'doctrina', '28', 'sda'],
    },
    aboutHistory: {
      title: 'Nuestra Historia',
      keywords: ['historia', 'iglesia', 'origen'],
    },
    connect: {
      title: 'Conéctate',
      keywords: [
        'contacto',
        'correo',
        'teléfono',
        'ubicación',
        'llamar',
        'mapa',
        'direcciones',
        'dirección',
        'connect',
        'contact',
        'email',
        'phone',
        'personal',
      ],
    },
    give: {
      title: 'Diezmos y Ofrendas',
      keywords: ['dar', 'diezmo', 'ofrenda', 'donación', 'give', 'tithe', 'diezmos'],
    },
    team: {
      title: 'Conoce a nuestro equipo',
      keywords: ['personal', 'pastores', 'team'],
    },
    bulletin: {
      title: 'Boletín Semanal',
      keywords: ['programa', 'anuncios', 'bulletin'],
    },
    events: {
      title: 'Próximos Eventos',
      keywords: ['anuncios', 'noticias', 'calendario', 'programas', 'events'],
    },
    baptism: {
      title: 'Unirse a la Iglesia',
      keywords: ['bautismo', 'membresía', 'join'],
    },
    worship: {
      title: 'Adoración Sabática',
      keywords: ['servicio', 'liturgia', 'worship'],
    },
    fellowship: { title: 'Compañerismo', keywords: ['grupos', 'fellowship'] },
    roster: { title: 'Registro de Servicio', keywords: ['voluntario', 'roster'] },
    prayer: { title: 'Muro de Oración', keywords: ['peticiones', 'prayer'] },
    language: {
      title: 'Idioma',
      keywords: ['chino', 'español', 'inglés', 'traducir', 'language', 'ajustes'],
    },
    darkMode: {
      title: 'Modo oscuro',
      keywords: ['theme', 'dark mode', 'apariencia', 'ajustes', 'oscuro'],
    },
  },
};

export const getSearchableItems = (language: string): SearchableItem[] => {
  const labels = ALL_SEARCH_LABELS[language] || ALL_SEARCH_LABELS.en;

  return [
    { ...labels.home, icon: 'home', route: '/' },
    {
      ...labels.community,
      icon: 'account-group',
      route: '/community',
    },
    {
      ...labels.resources,
      icon: 'bookmark-multiple',
      route: '/resources',
    },
    {
      ...labels.bible,
      icon: 'book-cross',
      route: '/resources/bible',
    },
    {
      ...labels.hymnal,
      icon: 'music-note',
      route: '/resources/hymnal',
    },
    { ...labels.give, icon: 'gift', route: '/home/give' },
    { ...labels.darkMode, icon: 'theme-light-dark', route: '/you' },
    { ...labels.language, icon: 'translate', route: '/you/language' },
    { ...labels.aboutSDA, icon: 'information', route: '/home/about_sda' },
    { ...labels.aboutHistory, icon: 'history', route: '/home/about_my_church' },
    { ...labels.connect, icon: 'email', route: '/home/contact' },
    { ...labels.team, icon: 'account-multiple', route: '/home/team' },
    { ...labels.bulletin, icon: 'file-document-outline', route: '/home/bulletin' },
    { ...labels.events, icon: 'calendar-star', route: '/community' },
    { ...labels.baptism, icon: 'water-outline', route: '/community/baptism' },
    { ...labels.worship, icon: 'church', route: '/community/worship' },
    { ...labels.fellowship, icon: 'account-group', route: '/community/fellowship' },
    { ...labels.roster, icon: 'clipboard-text-outline', route: '/community/roster' },
    { ...labels.prayer, icon: 'hands-pray', route: '/community/prayer' },
  ];
};
