import { MaterialCommunityIcons } from "@expo/vector-icons";

export interface SearchableItem {
  title: string;
  keywords: string[];
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  route: string;
}

export const ALL_SEARCH_LABELS: Record<string, any> = {
  en: {
    searchPlaceholder: "Search app...",
    home: {
      title: "Home",
      keywords: ["welcome", "start", "pulse", "livestream", "happening"],
    },
    community: {
      title: "Community",
      keywords: [
        "events",
        "schedule",
        "sabbath",
        "groups",
        "calendar",
        "volunteer",
        "in-person",
        "hub",
        "service",
        "fellowship",
        "small groups",
        "gathering",
        "roles",
      ],
    },
    resources: {
      title: "Resources",
      keywords: [
        "video",
        "preach",
        "message",
        "bible",
        "hymnal",
        "spiritual",
        "scripture",
        "worship",
        "sermons",
        "watch",
        "listen",
        "library",
        "pdf",
        "devotional",
        "youtube",
        "spotify",
        "podcast",
        "archive",
        "reader",
      ],
    },
    bible: {
      title: "Holy Bible",
      keywords: ["scripture", "word", "verse", "read", "chapter", "testament"],
    },
    hymnal: {
      title: "Hymnal",
      keywords: ["songs", "lyrics", "music", "sing", "worship", "praise"],
    },
    about: { title: "About Us", keywords: ["history", "beliefs", "church"] },
    connect: {
      title: "Connect",
      keywords: [
        "contact",
        "email",
        "phone",
        "location",
        "call",
        "map",
        "directions",
        "address",
        "staff",
      ],
    },
    give: {
      title: "Give",
      keywords: ["tithe", "offering", "donation", "tithing"],
    },
    language: {
      title: "Language",
      keywords: ["chinese", "spanish", "english", "translate", "settings"],
    },
    darkMode: {
      title: "Dark Mode",
      keywords: ["theme", "appearance", "night", "settings", "dark"],
    },
  },
  zh: {
    searchPlaceholder: "搜尋...",
    home: {
      title: "首頁",
      keywords: ["歡迎", "開始", "home", "脈搏", "直播"],
    },
    community: {
      title: "教會社群",
      keywords: [
        "活動",
        "時間表",
        "安息日",
        "小組",
        "義工",
        "calendar",
        "community",
        "中心",
        "服事",
        "團契",
        "聚會",
        "小組",
      ],
    },
    resources: {
      title: "資源庫",
      keywords: [
        "視頻",
        "證道",
        "信息",
        "聖經",
        "詩歌",
        "sermons",
        "resources",
        "圖書館",
        "靈修",
        "敬拜",
        "收看",
        "收聽",
        "youtube",
        "spotify",
        "podcast",
        "檔案",
      ],
    },
    bible: {
      title: "聖經",
      keywords: ["經文", "閱讀", "聖言", "scripture", "bible"],
    },
    hymnal: {
      title: "詩歌本",
      keywords: ["讚美詩", "歌詞", "音樂", "敬拜", "hymnal", "music"],
    },
    about: { title: "關於我們", keywords: ["歷史", "信仰", "教會", "about"] },
    connect: {
      title: "聯繫我們",
      keywords: [
        "聯絡",
        "電子郵件",
        "電話",
        "地點",
        "電郵",
        "地圖",
        "導航",
        "地址",
        "路線",
        "connect",
        "contact",
        "email",
        "call",
        "map",
        "同工",
      ],
    },
    give: {
      title: "捐獻",
      keywords: ["什一", "奉獻", "捐款", "give", "tithe", "tithing"],
    },
    language: {
      title: "語言設定",
      keywords: ["中文", "英文", "西班牙文", "翻譯", "language", "設定"],
    },
    darkMode: {
      title: "深色模式",
      keywords: ["theme", "dark mode", "主題", "外觀", "settings", "深色"],
    },
  },
  "zh-cn": {
    searchPlaceholder: "搜索...",
    home: {
      title: "首页",
      keywords: ["欢迎", "开始", "home", "脉搏", "直播"],
    },
    community: {
      title: "教会社区",
      keywords: [
        "活动",
        "时间表",
        "安息日",
        "日历",
        "小组",
        "义工",
        "calendar",
        "community",
        "中心",
        "服事",
        "团契",
        "聚会",
      ],
    },
    resources: {
      title: "资源库",
      keywords: [
        "视频",
        "证道",
        "信息",
        "圣经",
        "诗歌",
        "sermons",
        "resources",
        "图书馆",
        "灵修",
        "敬拜",
        "收看",
        "收听",
        "youtube",
        "spotify",
        "podcast",
        "存档",
      ],
    },
    bible: {
      title: "圣经",
      keywords: ["经文", "阅读", "圣言", "scripture", "bible"],
    },
    hymnal: {
      title: "诗歌本",
      keywords: ["赞美诗", "歌词", "音乐", "敬拜", "hymnal", "music"],
    },
    about: { title: "关于我们", keywords: ["历史", "信仰", "教会", "about"] },
    connect: {
      title: "联系我们",
      keywords: [
        "联络",
        "电子邮件",
        "电话",
        "电邮",
        "地点",
        "地图",
        "导航",
        "地址",
        "路线",
        "connect",
        "contact",
        "email",
        "phone",
        "call",
        "map",
        "同工",
      ],
    },
    give: {
      title: "捐献",
      keywords: ["什一", "奉献", "捐款", "give", "tithe"],
    },
    language: {
      title: "语言设置",
      keywords: ["中文", "英文", "西班牙文", "翻译", "language", "设置"],
    },
    darkMode: {
      title: "深色模式",
      keywords: ["theme", "dark mode", "主题", "外观", "settings", "深色"],
    },
  },
  es: {
    searchPlaceholder: "Buscar...",
    home: {
      title: "Inicio",
      keywords: ["bienvenido", "comenzar", "home", "pulso", "en vivo"],
    },
    community: {
      title: "Comunidad",
      keywords: [
        "eventos",
        "horario",
        "sábado",
        "grupos",
        "voluntario",
        "calendar",
        "community",
        "centro",
        "servicio",
        "compañerismo",
        "grupos",
        "reunión",
        "horario",
        "calendario",
      ],
    },
    resources: {
      title: "Recursos",
      keywords: [
        "video",
        "predicación",
        "mensaje",
        "biblia",
        "escritura",
        "adoración",
        "sermones",
        "ver",
        "escuchar",
        "himnario",
        "sermons",
        "resources",
        "biblioteca",
        "devocional",
        "youtube",
        "spotify",
        "podcast",
        "archivo",
      ],
    },
    bible: {
      title: "Santa Biblia",
      keywords: ["escritura", "palabra", "versículo", "leer", "testamento"],
    },
    hymnal: {
      title: "Himnario",
      keywords: ["cantos", "letras", "música", "cantar", "adoración"],
    },
    about: {
      title: "Sobre Nosotros",
      keywords: ["historia", "creencias", "iglesia", "about"],
    },
    connect: {
      title: "Conéctate",
      keywords: [
        "contacto",
        "correo",
        "teléfono",
        "ubicación",
        "llamar",
        "mapa",
        "direcciones",
        "dirección",
        "connect",
        "contact",
        "email",
        "phone",
        "personal",
      ],
    },
    give: {
      title: "Dar",
      keywords: ["diezmo", "ofrenda", "donación", "give", "tithe", "diezmos"],
    },
    language: {
      title: "Idioma",
      keywords: [
        "chino",
        "español",
        "inglés",
        "traducir",
        "language",
        "ajustes",
      ],
    },
    darkMode: {
      title: "Modo oscuro",
      keywords: ["theme", "dark mode", "apariencia", "ajustes", "oscuro"],
    },
  },
};

export const getSearchableItems = (language: string): SearchableItem[] => {
  const labels = ALL_SEARCH_LABELS[language] || ALL_SEARCH_LABELS.en;

  return [
    { ...labels.home, icon: "home", route: "/" },
    {
      ...labels.community,
      icon: "account-group",
      route: "/community",
    },
    {
      ...labels.resources,
      icon: "bookmark-multiple",
      route: "/resources",
    },
    {
      ...labels.bible,
      icon: "book-cross",
      route: "/resources/bible",
    },
    {
      ...labels.hymnal,
      icon: "music-note",
      route: "/resources",
    },
    { ...labels.give, icon: "gift", route: "/you" },
    { ...labels.darkMode, icon: "theme-light-dark", route: "/you" },
    { ...labels.language, icon: "translate", route: "/you/language" },
    { ...labels.about, icon: "information", route: "/you/about" },
    { ...labels.connect, icon: "email", route: "/you/contact" },
  ];
};
