import {
  DEFAULT_TEXT_SCALE,
  scaleTypographyMetric,
  type TextScale,
} from '@/constants/AppPreferences';
import { StyleSheet } from 'react-native';

/**
 * Shared styles for the Bible Reader and other immersive reading components.
 */
export const createReaderStyles = (textScale: TextScale) => StyleSheet.create({
  readerContainer: { flex: 1 },
  readerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    zIndex: 10,
    height: 56,
  },
  bottomSelectorBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 0.5,
    zIndex: 100,
  },
  backButton: { padding: 15 },
  selectorRow: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-start',
    gap: 8,
    paddingRight: 15,
  },
  selector: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  selectorText: {
    fontWeight: '700',
    fontSize: scaleTypographyMetric(13, textScale),
    lineHeight: scaleTypographyMetric(18, textScale),
  },
  bibleScroll: { flex: 1 },
  bibleContent: { padding: 20, paddingBottom: 80 },
  verseText: {
    fontSize: scaleTypographyMetric(19, textScale),
    lineHeight: scaleTypographyMetric(30, textScale),
    marginBottom: 14,
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  verseNumber: {
    fontSize: scaleTypographyMetric(14, textScale),
    lineHeight: scaleTypographyMetric(28, textScale),
    fontWeight: '600',
    paddingRight: 6,
  },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },

  // Selection Overlays / Modals
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 0.5,
  },
  modalTitle: {
    paddingHorizontal: 16,
    marginBottom: 12,
    textAlign: 'center',
  },
  controlDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    overflow: 'hidden',
  },
  dockInner: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  pillsContainer: {
    flexDirection: 'row',
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 0,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 22,
    gap: 4,
    height: 44,
    minWidth: 0,
    flexShrink: 1,
    flexGrow: 1,
  },
  sideSlot: {
    width: 48,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPlaceholder: { width: 44 },
  navIcon: { margin: 0, width: 44 },
  pillText: {
    fontSize: scaleTypographyMetric(15, textScale),
    lineHeight: scaleTypographyMetric(20, textScale),
    fontWeight: '600',
  },
  audioControlText: {
    fontSize: scaleTypographyMetric(14, textScale),
    lineHeight: scaleTypographyMetric(20, textScale),
    fontWeight: '700',
  },
  audioTimeText: {
    fontSize: scaleTypographyMetric(11, textScale),
    lineHeight: scaleTypographyMetric(16, textScale),
  },
  audioDock: {
    height: 84,
    paddingHorizontal: 12,
  },
  audioControlRow: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  audioTransportControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  audioAction: { margin: 0 },
  audioPlayButton: { marginHorizontal: 2, marginVertical: 0 },
  audioSideControl: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  timerBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  audioTimelineRow: {
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  audioScrubberTouchTarget: { height: 28, flex: 1, justifyContent: 'center' },
  audioTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(128, 128, 128, 0.18)',
    position: 'relative',
  },
  audioBufferedTrack: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 2,
  },
  audioPlayedTrack: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 2,
  },
  audioThumb: {
    position: 'absolute',
    top: -5,
    width: 14,
    height: 14,
    borderRadius: 7,
    marginLeft: -7,
  },
  scrollContent: { paddingHorizontal: 20 },
  loader: { marginTop: 50 },
  heading: {
    fontSize: scaleTypographyMetric(20, textScale),
    fontWeight: '800',
    marginTop: 32,
    marginBottom: 8,
  },
  verseContainer: {
    fontSize: scaleTypographyMetric(18, textScale),
    lineHeight: scaleTypographyMetric(28, textScale),
    marginBottom: 12,
  },
  hebrewSubtitle: {
    fontSize: scaleTypographyMetric(16, textScale),
    marginBottom: 16,
    opacity: 0.8,
  },
  inlineHeading: {
    fontWeight: '700',
    fontSize: scaleTypographyMetric(14, textScale),
    lineHeight: scaleTypographyMetric(24, textScale),
  },
  footnoteMarker: {
    fontSize: scaleTypographyMetric(12, textScale),
    fontWeight: 'bold',
    position: 'relative',
    top: -6,
    paddingHorizontal: 2,
  },
  lineBreak: { height: 16 },
  poemText: {},
  modalScroll: { padding: 16, flexShrink: 1 },
  detailSection: { marginBottom: 20 },
  detailText: {
    fontSize: scaleTypographyMetric(16, textScale),
    lineHeight: scaleTypographyMetric(24, textScale),
  },
  modalContent: { margin: 20, borderRadius: 12, maxHeight: '80%', overflow: 'hidden' },
  modalInner: { paddingVertical: 16, flexShrink: 1 },
  title: {
    fontSize: scaleTypographyMetric(20, textScale),
    fontWeight: '800',
    lineHeight: scaleTypographyMetric(28, textScale),
  }, // Alias to prevent 'undefined' errors
  modalItem: {
    padding: 18,
    borderBottomWidth: 0.5,
  },
  modalItemText: {
    fontSize: scaleTypographyMetric(16, textScale),
    lineHeight: scaleTypographyMetric(22, textScale),
  },
});

export const ReaderStyles = createReaderStyles(DEFAULT_TEXT_SCALE);
